### ISSUE TITLE
Write brief article "Better Testing: Start Today"

### ISSUE THREAD

**Issue by maherou** [betterscientificsoftware/betterscientificsoftware.github.io#1]
Better Testing: Start Today

Concerned about testing, but so hard to cover existing code, not enough resources.
Instead, resolve to cover new functionality with tests.
From now on:
- No source contributions without tests.
- A source checkin without tests coverage is a fault.  Can and should be reported by anyone.

**Comment by bartlettroscoe** [comment]
You might want to add no changing code before making sure it is covered with tests.  That is basically the Legacy Software Change Algorithm:

* http://trac.trilinos.org/wiki/TribitsLegacySoftwareChangeAlgorithm

BTW, do you want to transfer that page to this BSS site?

**Comment by rinkug** [comment]
We have published several testing resources on bssw.io since this ticket was opened. So, this is being closed.
