### ISSUE TITLE
Resource listings - add author

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#102]
Can we programmatically present author with each resource? (Intended as meta data, not to be linked to author page)

**Comment by clararaubertas** [comment]
Should be fixed!

**Comment by sbxchicago** [comment]
Not seeing authors in resource listings. Was I clear that it should be present on listing page?

**Comment by clararaubertas** [comment]
Ah, listing page! Will add.

**Comment by clararaubertas** [comment]
Should be added.
