### ISSUE TITLE
Site Contributors - Affiliations

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#104]
Clara - we'd like to add institutional affiliations to the contributors page (shown on p25 of WF). Does that require Lois to create pages for each author? Or is there a simpler way to do this?

**Comment by clararaubertas** [comment]
I believe we can get this via the GitHub API, since we will have a GitHub user ID for every contributor (right?). I'll work on this!

**Comment by sbxchicago** [comment]
Correct, the user account/ ID is a requirement for contributors. THanks.

**Comment by clararaubertas** [comment]
Affiliations now listed on the contributors page!
