### ISSUE TITLE
Refine results - results needs to be limited to resources

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#105]
I'm seeing What Is How To as well as the /resources/3

**Comment by clararaubertas** [comment]
Can you let me know steps to recreate this problem? thanks!

**Comment by sbxchicago** [comment]
Good point. The problem is probably global, but I can see it for some topics and not others when I refine results. Starting at All Resources and moving through topics in the first category, Better Collaboration goes like this:
- Documentation - contains How To, What IS and displays /resources/1 and /resources/29
- Licensing - contains a What Is
- Strategies... - contains What Is, How To, What are and /resources/29
- Version Control - contains What Is, How To 
- Issue tracking - contains What Is

In some cases removing a WhatIS or How To will be the only item that displays, but then it'll be up to BSSw to create more resources

**Comment by curfman** [comment]
We are working toward having at least 1 resource (beyond WhatIs, HowTo) for each topic by the time of site launch.  For the purpose of testing the site now, would it be helpful for us to insert some skeleton resources, where these do not yet exist?  Let us know; we could do that quickly if it is useful.

Lois

**Comment by sbxchicago** [comment]
I should point out another way I'm testing this. 

Going from Home > Better Collaboration > See All Documentation Resources should yield the same results as going from Home > All Resources > Refine Results > checking Documentation box. 

Looking across categories right now, accessing a topic through the category page seems to produce cleaner results while Refine Results pathway displays more results and adds What Is, How To and the oddly named resources (/resources/29)

**Comment by sbxchicago** [comment]
Unless Clara feels she doesn't have enough resources to test, I'd suggest you hold off on placeholder resources. We don't need to put extra work on your plate and I'm OK with results coming up empty until you get resources in place. In fact it will ensure the site doesn't look overly populated when you are evaluating the state of resources.

**Comment by clararaubertas** [comment]
should be fixed!
