### ISSUE TITLE
Communities Overview - Subnav links

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#106]
Page title and deck (a.k.a the first paragraph) should appear in hero area along with subnav links. The rest of page content will appear in main page area. (Subnav links need to be corrected but this is a separate issue)

**Comment by sbxchicago** [comment]
I just noticed that this page is incorrect in the wireframes since it doesn't show subnav in place. Reference the Get Oriented: Site Overview wireframe I sent to you yesterday.

**Comment by clararaubertas** [comment]
What page is this referring to? Thanks!

**Comment by clararaubertas** [comment]
I think we are good with subnav now -- can you confirm?
