### ISSUE TITLE
Landing pages - how does Lois handle misc. text 

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#109]
On landing pages such as blog, events and homepage there are chunks of text Lois needs to provide — the decks for instance — that don't merit a page of their own. Could she combine into a single doc and provide to you? Is there a better approach?

**Comment by clararaubertas** [comment]
Should this text be hard-coded or editable?
If hard-coded, just send to me.
If editable, the best approach is probably to create pages with these titles and enter the content there.

**Comment by sbxchicago** [comment]
Covered in other issue
