### ISSUE TITLE
Site contributors - Hero are needed

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#112]
This page needs a page title and placeholder deck.

**Comment by clararaubertas** [comment]
Where will this text come from? Should it be hard-coded in or come from github?

**Comment by sbxchicago** [comment]
If we can easily have the pages Indicate the page title, deck , and paragraph(s) below deck then we should do it to allow editing by BSSw team. 

This issue carries over to Site contributors, homepage, Blog, Events, possibly others. The pages exist in repo but in the case of Blog and Events aren't indicative of what's showing on the prototype. 

Any unforeseen problems doing this?

**Comment by clararaubertas** [comment]
OK, we will use 'Blog' and 'Events' page data to feed content displayed above blog/event listings.

**Comment by clararaubertas** [comment]
We will need to know the name of the page feeding text for the contributors index as well.

**Comment by sbxchicago** [comment]
So Lois should create a Contributors page as well?

**Comment by sbxchicago** [comment]
Lois adding Contributors page

**Comment by curfman** [comment]
Done, commit 6712a02f21a0f5fc024d981c31409c44a6632a45
