### ISSUE TITLE
Harmonize granularity of content items

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/betterscientificsoftware.github.io#114]
At the moment, the contributions vary in granularity from single resources to multiple resources associated with a topic.  Eventually, it would be nice to set some guidelines for how we want to do this and morph the existing content to follow these guidelines.

(I realize, however, that this is not as urgent as getting content that spans the desired space.)

**Comment by rinkug** [comment]
This is work in progress. Most of curated content is done but needs to be 100% complete.  We need to replace one liners by more content rich pages.

**Comment by rinkug** [comment]
Emailed Lois (10/21) @curfman

**Comment by curfman** [comment]
Agree; thank you.

**Comment by rinkug** [comment]
This was completed AFAIK.
