### ISSUE TITLE
About/Team - How should Lois set up team members?

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#116]
Lois would like to add pages for team members to be pulled into the about page. Can you prescribe specific metadata that will ensure this works with your parsing process?

**Comment by clararaubertas** [comment]
We will parse team member info using the GitHub API. Is there a wireframe that shows what info we need and in what format it should be displayed?

**Comment by sbxchicago** [comment]
Yep, p13 in 4/10/17 wireframe set. We can cover questions on call.
