### ISSUE TITLE
Resource/Subresources - omnibus page

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#117]

**Comment by sbxchicago** [comment]
Lois,

It would be helpful for Clara if there is a resource established with sub-resources that we take it further and activate ALL content areas. In all likelihood this would not be a real resource. It would include images (no resources have images yet), tables, bold text emphasis text, all header types, links related to sub resources, etc. Your guide would be the fully realized visual comp we presented this week. (please disregard previous wireframe). 

We call it an omnibus (aka kitchen sink) example page.

**Comment by rinkug** [comment]
This exists is some form now and can be closed.
