### ISSUE TITLE
Add content on Gitlab for CI Testing

### ISSUE THREAD

**Issue by louisvernon** [betterscientificsoftware/betterscientificsoftware.github.io#12]
Add initial content

**Comment by louisvernon** [comment]
I have an existing presentation I developed for LANL on Gitlab CI. It is specific to our Gitlab and CI infrastructure. I would ideally like to expand on this and make this the basis of in depth original content.

For a shorter curated piece I plan to use the following documentation.

NERSC PPTX and Demo Repo:
https://drive.google.com/drive/folders/0B9YE8zJ_-RYcQ0dJVkVMZU0wNG8
https://www.nersc.gov/assets/Uploads/2017-02-06-Gitlab-CI.pdf
 
Gitlab Youtube Link:
https://www.youtube.com/watch?v=1iXFbchozdY
 
Possible (more advanced) - Static Code Analysis (CERN):
https://cds.cern.ch/record/2210418/files/Datko.pdf

**Comment by louisvernon** [comment]
@junghans Any other resources you would recommend for a short curated list of references for Gitlab CI? The NERSC resource is pretty good (although there are some NERSC/LBL specific slides).

**Comment by fpnick** [comment]
Personally, I think the Gitlab pages themselves are a pretty valuable resource for setting up CI with Gitlab. I think I pretty much set up our (very basic) CI in Gitlab based only on those pages: https://docs.gitlab.com/ee/ci/README.html

I also set up automated scaling tests of our software on our cluster with Gitlab CI. I'd be happy to contribute a few words, if you need help ;)

**Comment by junghans** [comment]
This is for @pagrubel now!

**Comment by rinkug** [comment]
This should be closed now? But, we should write on CI testing on ECP later?
