### ISSUE TITLE
Guide and template to setup CI on github using Travis

### ISSUE THREAD

**Issue by junghans** [betterscientificsoftware/betterscientificsoftware.github.io#123]
I have started working on this here:
https://github.com/junghans/travis-docker-glue

@markcmiller86 and @maherou have access to.

@louisvernon and @junghans: I will mentor a student to write a setup guide document.

**Comment by junghans** [comment]
Hello @pagrubel!

**Comment by junghans** [comment]
Here are the repos @laurelmcintyre made:
https://github.com/laristra/python-ci
https://github.com/laristra/c-makefile
https://github.com/laristra/c
https://github.com/laristra/buildenv
https://github.com/laristra/ccmake-docker
https://github.com/laristra/cpp-cmake
and the documentation:
https://github.com/laristra/documentation

**Comment by pagrubel** [comment]
Blaming the yo yo behavior on my mac

**Comment by rinkug** [comment]
Emailed Pat and Mark @pagrubel  and @markcmiller86 on Oct 18 to update this issue

**Comment by markcmiller86** [comment]
Closing because I aniticiate IDEAS-ECP collaboration with ECP-CI team (primarily via @markcmiller86) will produce material @junghans was hoping to see and then we can create CC here that will point at it.
