### ISSUE TITLE
Add curated content and link to Udacity: Software Testing Tutorial: How to Make Software Fail

### ISSUE THREAD

**Issue by elaineraybourn** [betterscientificsoftware/betterscientificsoftware.github.io#126]
I will link to this url: https://www.udacity.com/course/software-testing--cs258

**Comment by bernhold** [comment]
Elaine, it is already in.  Please see  	SwTestingUdacity.md.

Review and improvements would certainly be welcome.

**Comment by elaineraybourn** [comment]
Thanks, David.

**Comment by rinkug** [comment]
Already published at https://bssw.io/items/understanding-software-testing-and-how-to-make-software-fail
