### ISSUE TITLE
Add curated resource for book "Working Effectively with Legacy Code" by M. Feathers.

### ISSUE THREAD

**Issue by curfman** [betterscientificsoftware/betterscientificsoftware.github.io#128]

**Comment by bartlettroscoe** [comment]
What I would do for this is to copy and edit what I wrote for Trilinos at:

* http://trac.trilinos.org/wiki/TribitsLegacySoftwareChangeAlgorithm

For me, the Legacy Software Change Algorithm is the most important contribution from that book.

The content on that page is longer than most of the existing contributions for the BSS website but I think that summary is pretty good and is not all that long.

@maherou, what do you think about this appraoch?

**Comment by bartlettroscoe** [comment]
Another option is to create a How-To and What-Is for the Legacy Software Change Algorithm.  The How-To document could be called "What is Legacy Code and the Legacy Software Change Algorithm?".  The What-Is document could be called "How to apply the Legacy Software Change Algorithm".  Then the BSS site could just provide a short overview and link to these.

What about that approach?

**Comment by curfman** [comment]
Hi Ross -- Mike and I discussed, and we agree that it would be great to develop a variant of the second option: WhatIs and HowTo docs, following the 2-page (or less) format used for prior WhatIs and HowTo docs.  Let's follow up offline to discuss approach, including incorporating input from Mark Miller.  Thanks.

**Comment by bartlettroscoe** [comment]
Sorry, I did not see this when I created #331.  I will close this one as duplicate since I put #331 in the commits in PR #332.
