### ISSUE TITLE
Want to be able to link to a whole topic or a topic search

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/betterscientificsoftware.github.io#133]
There are cases where rather than linking to individual curated content resources, I'd like to be able to point users to a whole topic.  The natural result of following the link would be a list of all of our content under that topic.

I don't know whether this is possible now, with a properly constructed link, or a capability we might be able to add in the future, but I think it would be useful.

**Comment by rinkug** [comment]
This is done.
