### ISSUE TITLE
Site Contributors - Display blog posts and change resource label

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#135]
Include number of blog posts and resources will be relabeled as "resource(s) or prerequisite(s)" (Due to the fact WhatIS are included in listing)

**Comment by clararaubertas** [comment]
This has been adjusted. Let me know if the formatting here should change!

**Comment by sbxchicago** [comment]
In this display it will be important to distinguish between "Resource or Prerequisite" and "Blog post". So disaggregate results. Is this fairly easy?

**Comment by clararaubertas** [comment]
should be fixed!

**Comment by clararaubertas** [comment]
waiting on confirmation whether this currently displays correctly.
