### ISSUE TITLE
Create "mini-whatis" for software distribution

### ISSUE THREAD

**Issue by jwillenbring** [betterscientificsoftware/betterscientificsoftware.github.io#138]
Done for this includes:

1. A 2-line description of topic on:
[https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/Site/Categories/Planning.md](https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/Site/Categories/Planning.md)

2. A half page of text in a new file located here:

[https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/Site/Categories/Topics/WhatIsDeployment.md](https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/Site/Categories/Topics/WhatIsDeployment.md)

Target completion for this is May 26, 2017.

**Comment by jwillenbring** [comment]
@curfman 

I propose to narrow the focus of this what is from deployment to CSE Software Deployment, and change the location of the file to:

https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/Site/Categories/Topics/WhatIsCseSwDeployment.md

**Comment by curfman** [comment]
Sounds good; thanks.

**Comment by jwillenbring** [comment]
Looking at the possibility of changing the focus of this from deployment to delivery, distribution, or some other term that is more general and better describes what we currently do.

**Comment by jwillenbring** [comment]
Changing the focus from deployment to distribution would result in a file location of:

[https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/Site/Categories/Topics/WhatIsCseSwDeployment.md](https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/Site/Categories/Topics/WhatIsCseSwDeployment.md)

**Comment by jwillenbring** [comment]
Additionally, @curfman mentioned the topic of deployment has been move under the software development category, so it will go on the page:

[https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/Site/Categories/Development.md](https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/Site/Categories/Development.md)

**Comment by rinkug** [comment]
This is done: https://bssw.io/items/what-is-cse-software-distribution
