### ISSUE TITLE
Create Software Engineering Community content for the Community page

### ISSUE THREAD

**Issue by jwillenbring** [betterscientificsoftware/betterscientificsoftware.github.io#139]
Done for this is to fill out the stub page for the software engineering community at:

[https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/Site/Communities/SoftwareEngineering.md](https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/Site/Communities/SoftwareEngineering.md)

**Comment by rinkug** [comment]
This is done and can be closed.
