### ISSUE TITLE
Mini-whatis docs - treat differently from resource

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#140]
When you access a what is doc on the site, it takes you to a min-whatis page that is a text version of a whatis that also has a listing of whatis/howto docs. 

I have a question with a few contingencies. 

First, let's remember that at some point ALL whatis docs will link to PDFs, these mini-whatis docs will go away and the link will simply go to a PDF in the browser. So let's not go big-budget with a complicated solution. 

I'd like to have the mini-whatis docs NOT include the what is/howto docs of their topic. This will mean they are different from resources. Is that complicated?

Is there an easy way to go about this. 

I'm including Lois to monitor responses and chip in advice.

**Comment by clararaubertas** [comment]
Can you give examples of the two kinds of pages ("whatis" and "miniwhatis")? Are these pages named diffrerently, or do they have different metadata?

**Comment by curfman** [comment]
Hi Clara —

The mini-WhatIs docs are brief versions of WhatIs docs.  They follow the same naming convention (WhatIsXXX, WhatAreXXX) and use the same metadata (all are Level 0 files).  The only difference is that the mini-WhatIs docs are much shorter than the 2-page WhatIs docs.  Over time, we might transition some of the mini-WhatIs docs to full WhatIs docs, depending on priorities for site content.

The plan is for each topic on the site (as shown in the Style Guide) to have at a mini-WhatIs or WhatIs doc to define terminology and scope on the site, and to be used in the forthcoming resource map.   We still have a few more topics to go.

The mini-WhatIs docs are here (*.md files):
https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/tree/master/Site/Categories/Topics

For example:
https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/Site/Categories/Topics/WhatAreDisussionForumsAndQASitesForBetterScientificSw.md

https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/Site/Categories/Topics/WhatIsIssueTracking.md

The various WhatIs docs currently are available as curated content on the site, pointing to external *.pdf files:

https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/WhatIsGoodDocumentation.md

https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/WhatIsVersionControl.md

**Comment by clararaubertas** [comment]
OK -- if I understand correctly, the request is to not have "whatis" links show up on documents that are themselves a whatis, and it sounds like there's no important distinction on my end between whatis and miniwhatis. 
I've made the change so that these links don't show up on those pages. Let me know if this solves this or if there are more concerns!

**Comment by clararaubertas** [comment]
What we need for this: add some examples of WhatIs that are links to PDFs.

**Comment by curfman** [comment]
Here are 2 examples: 

The various WhatIs docs currently are available as curated content on the site, pointing to external *.pdf files:

https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/WhatIsGoodDocumentation.md

https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/WhatIsVersionControl.md

**Comment by clararaubertas** [comment]
OK, I believe we are all good with handling the different WhatIs docs in the same manner. Please confirm!

**Comment by rinkug** [comment]
This is  not needed now. Can be closed.
