### ISSUE TITLE
Category pages - modifications

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#144]
Changes to match the latest wireframes (WFs dated 5/11/17, available on BCamp)

1 - In .md file Lois included: "**Description:**  Methods for testing and verification to ensure that software is robust and produces reliable results." This should be the Deck. Is there a problem in how she entered this so that it's not displaying correctly? 

2 - each category page should present a link "See All Better Reliability Reources" after the intro paragraph and before the H2 (Better Reliability Topics)

**Comment by clararaubertas** [comment]
We were showing Overview instead of Description -- fixed now.

The other change is made as well.
