### ISSUE TITLE
All resources - hide text : "For more information on better scientific..."

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#147]
BSSw has included stock text on each resource: For more information on better scientific software, go to the Better Scientific Software main page.

We discussed this on Tuesday's call. They want this present for search purposes, but not visible by site users.

**Comment by clararaubertas** [comment]
waiting on confirmation for this because it seems to still be undecided: https://basecamp.com/1948695/projects/13043991/messages/69614220

**Comment by clararaubertas** [comment]
AFAIK it has been decided not to do this... please confirm.

**Comment by curfman** [comment]
Removed this text from all resources; done.
