### ISSUE TITLE
Resource with sub-resources not appearing in all resources listing

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#148]
To my knowledge, there is only one resource that contains sub-resources: http://bss.parallactic.com/resources/documentation-tools
1.
The Resource is not the resource listing (and neither are sub-resources which is great). 
2. 
Going to Better Development category page and choosing Documentation it doesn't call up the resource.
3.
But when I search for the Resource it appears in search results along with its sub resources. Ideally I'd like to fix search so that it doesn't call up sub-resources? Nice-to-have, not essential.

**Comment by clararaubertas** [comment]
OK, this is now adjusted so that the base resource is found in the resource listing, and the subresources are not found in search.
