### ISSUE TITLE
Add a placeholder announcement

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#152]
Erica needs an active announcement with a sunset date far in the future. 

As a reminder, an announcement is an event or blog post that is promoted to an announcement.

**Comment by clararaubertas** [comment]
please note announcements are in this file: https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/Site/Announcements/Announcements-2017.md
(just in case there is any confusion: promoting to an announcement involves adding to this file, not modifying the event or blog post file)

**Comment by clararaubertas** [comment]
there are now two announcements displayed, with start dates in the far future.

**Comment by sbxchicago** [comment]
Thanks for clarifying the method of adding announcements for us and thanks for adding placeholders. I want to clarify that our intention is to programmatically limit the announcement to only the most recently posted announcement. At any time only one should appear in header of homepage.

**Comment by clararaubertas** [comment]
"Most recently posted" isn't actually something we can determine from the Announcements.md file... we could do earliest start date or end date of the eligible announcements, or BSS could delete old announcements when they edit the file. Let me know what seems best.

**Comment by sbxchicago** [comment]
I get it now. We'll rely on them removing/replacing announcements keeping one live at a time at most.
