### ISSUE TITLE
Refined resource listing: Topics chosen should be displayed along with number of resources

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#154]
After results are refined we want a line to appear below refine results that says "Viewing Results For" and is followed by every topic that is selected in sequence separated by commas. The string ends with the amount of resources displayed (##).

If all topic are selected it would say Viewing All Topics (##) 

We want to impose a character count in case too many topics are selected. We would like to avoid running two rows and pushing results further down the page. Ideally the topics would be truncated follwoed by an elipses and have the number shown. "... (XX)"

Can you suggest your best idea for approaching this?

**Comment by clararaubertas** [comment]
made this adjustment -- see http://bss.parallactic.com/resources?topics%5B%5D=2&topics%5B%5D=3&topics%5B%5D=12&topics%5B%5D=39&topics%5B%5D=1&topics%5B%5D=7&topics%5B%5D=13&topics%5B%5D=26&topics%5B%5D=27&topics%5B%5D=31#
