### ISSUE TITLE
Strange Breadcrumbs: Documentation Tools Resource

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#158]
Breadcrumbs for Documentation Tools Resource (http://bss.parallactic.com/resources/documentation-tools) seems to indicate subresources as separate path. Can we disable/hide this?

Home > [Import From Subresources] 
Home > Better Development Documentation

**Comment by clararaubertas** [comment]
"Import From Subresources" is listed as a topic on that resource -- editing https://raw.githubusercontent.com/betterscientificsoftware/betterscientificsoftware.github.io/7734a70950421d2bc8dc34fe827fccf2ce6690b9/CuratedContent/DocumentationTools.md to no longer list that topic will solve this.

**Comment by clararaubertas** [comment]
Per email request: changed parsing to no longer import topics with names in brackets.
