### ISSUE TITLE
Write mini-WhatIs: Reproducibility

### ISSUE THREAD

**Issue by curfman** [betterscientificsoftware/betterscientificsoftware.github.io#159]
Write a mini-WhatIs for the topic of Reproducibility: 

(1) Edit the Reliability category page:
https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/Site/Categories/Reliability.md 

Replace the placeholder text for ‘Reproducibility’ with your new text.

(2) Create a new file: WhatIsReproducibility.md, to be located here:  
https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/Site/Categories/Topics/WhatIsReproducibility.md 

Write about half page of text to explain this topic.

**Comment by maherou** [comment]
These files have been created and updated.
