### ISSUE TITLE
contributor list

### ISSUE THREAD

**Issue by clararaubertas** [betterscientificsoftware/betterscientificsoftware.github.io#172]
fix contributor list for resources list

**Comment by clararaubertas** [comment]
fixed!

**Comment by sbxchicago** [comment]
Can this vary between "Contributor" for a single contributor and "Contributors" if multiple contributors?

**Comment by clararaubertas** [comment]
ok, fixed!

**Comment by sbxchicago** [comment]
Aw... I was caught snoozing... as per a recent change, resource listings are supposed to display TOPIC not CONTRIBUTOR/s. 

(This might be a duplicate issue.)

**Comment by clararaubertas** [comment]
this is fixed!
