### ISSUE TITLE
staff page

### ISSUE THREAD

**Issue by clararaubertas** [betterscientificsoftware/betterscientificsoftware.github.io#174]
import staff pictures for about page

**Comment by clararaubertas** [comment]
OK, staff and pictures now displayed on about page!

**Comment by sbxchicago** [comment]
On About page we want the photos pulled from Github but not the other info that is coming from the contributors page. We want to display the text entered on About.md, we intend more to be added in the future.

To be specific:
- we want the header that says BSSw Editorial Team to display
- for each team member a photo is pulled form GH
- below the photo we want the contact's name, the lab name
- in the future a role may be entered above the contact's name and a sentence or two will be entered below the lab name.

**Comment by clararaubertas** [comment]
OK -- this is adjusted to just add GH photos to the existing text on the page.
