### ISSUE TITLE
check prerequisites

### ISSUE THREAD

**Issue by clararaubertas** [betterscientificsoftware/betterscientificsoftware.github.io#175]
http://bss.parallactic.com/resources/keeping-your-vision-fit-for-years-of-software-development has blank prereqs and shouldn't

**Comment by sbxchicago** [comment]
Other resources missing prereq's: 
http://bss.parallactic.com/resources/an-introduction-to-software-licensing
http://bss.parallactic.com/resources/choose-an-open-source-license
http://bss.parallactic.com/resources/contributor-agreements
http://bss.parallactic.com/resources/free-software-foundation-licensing-compliance-team
http://bss.parallactic.com/resources/open-source-initiative
http://bss.parallactic.com/resources/software-engineering-for-computational-science-workshop-series
http://bss.parallactic.com/resources/test-with-images
http://bss.parallactic.com/resources/test-with-images-2

**Comment by clararaubertas** [comment]
It looks like these prerequisites are actually missing from the system -- I'm not finding any "What Is Licensing" or "What Is Personal Productivity and Sustainability" resources in the GH repo.

**Comment by sbxchicago** [comment]
I'll talk to Lois about the prerequisites and get back to you.
