### ISSUE TITLE
Search Results - should present number of results

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#185]
In search results, the number of items should be included in parenthesis
Search
Result(s) found for “search term” (XX)

**Comment by clararaubertas** [comment]
OK, fixed!

**Comment by sbxchicago** [comment]
Can results easily be displayed as: Results found for “search term” (XX) rather than the way it is now?

And the XX would be the number of results? This is desired so it follows similar logic as the tallies that appear in refine results.

**Comment by clararaubertas** [comment]
OK, changed!
