### ISSUE TITLE
Community pages - resources at bottom of page should list as "proto footer"

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#191]
Communities have resources assigned to them, this should be pulled in the way blog  are associated on the blog. 

Do you need to do something on your end if Lois provides a URL? or can you coach Lois on what to do? Or is this a front end thing?

**Comment by clararaubertas** [comment]
We'll need metadata in resources to do this -- the same format we've used for categories should work. Let me know when we have some sample resources associated with communities and I'll get that imported/displayed.

**Comment by sbxchicago** [comment]
I'm looping Lois in on this because I;m not trusting myself to include the right metadata. For Lois's benefit, here are the resources by name. Lois, Clara would like the metadata... see thread above

Featured resources for the environmental system science community
- How to Write Good Documentation
- High Performing Teams at Google
- How to Improve Testing for CSE Software

Featured resources for the exascale computing community
- What Is Performance Portability for CSE Applications?
- How To Enable Performance Portability for CSE Applications
- High Performing Teams at Google

Featured resources for the scientific libraries community
- How to Configure Software
- Open Source Software Sustainability Resources
- Test Driven Development in Scientific Software: A Survey
- High Performing Teams at Google

Featured resources for the software engineering community
- How to Write Good Documentation
- Containers for Research Software

Featured resources for the exascale computing community
- What Is Performance Portability for CSE Applications?
- How To Enable Performance Portability for CSE Applications
- What Is Good Documentation
- How to Write Good Documentation
- What Is CSE Software Testing
- How To Improve Testing for CSE Software

**Comment by curfman** [comment]
Hi Clara -- We are considering this from the perspective of the community page maintainer specifying the resources to highlight (not the other way around).  So each community page already includes a bulleted list of highlighted resources.  We could change the community pages instead to specify the resources in metadata.  It is not practical though to edit the resources themselves to indicate correspondence with particular communities.  Likely we should discuss.

**Comment by clararaubertas** [comment]
Can you edit one of the community pages to have this data in the way you expect it to be specified?

This is doable -- just noting that it's adding some time to the project.

**Comment by curfman** [comment]
Done, see:

https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/Site/Communities/ExascaleComputing.md

https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/Site/Communities/ScientificLibraries.md

This includes highlighted resources that are events, (blog) articles, curated content.

**Comment by clararaubertas** [comment]
OK, this should be done! Let me know if this is working as you expect.

**Comment by curfman** [comment]
Thanks, Clara.  I noticed that the front-end content for highlighted resources does completely not match those in Github (I checked just the 2 communities listed above: Exascale Computing, Scientific Libraries).  Events do not appear; some extraneous items that are not resources appear; a few other inconsistencies. Hmmm ...

**Comment by clararaubertas** [comment]
OK, I'll check on that and get back to you!
