### ISSUE TITLE
Resource listing - topics should be presented as metadata

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#192]
Resource listing - topics should presented as metadata, currently contributors are

**Comment by clararaubertas** [comment]
done!

**Comment by sbxchicago** [comment]
As a result, visually, things broke. Should I talk to Erica?

**Comment by clararaubertas** [comment]
Yup! Let me know if the markup used there should change.

**Comment by sbxchicago** [comment]
I think we need an adjustment ... the topics shouldn't display with their own link. When you hover the  whole resource item it should take you to that resource. I think this is a markup thing.

**Comment by clararaubertas** [comment]
OK, fixed!
