### ISSUE TITLE
Site Contributors - number in listing of resources doesn't match amount indicated

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#194]
Site Contributors - linking to listing of resources SOMETIMES not matching up with amount indicated in resource/ prerequisite. Seems like its when it's more than just 1 or 2.  Roscoe Bartlett and Dan Ibanez, and Mark Miller are examples of not matching, but Mike Heroux and Christoph Junghans and others are correct.

**Comment by clararaubertas** [comment]
Should be fixed!
