### ISSUE TITLE
CHRON-JOB frequency?

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#195]
Clara, when you decide to establish the CHRON-JOB to timely push site updates live, can you let us know how frequently that will be happening?

**Comment by clararaubertas** [comment]
Whatever frequency you'd like! (Though it should probably not be more than ~ twice an hour, for server load reasons.)

This will get set up when we move over to BSS's server.

**Comment by sbxchicago** [comment]
How is server implementation going? Any obstacles of note? Aside from a lack of complete content in the site, any concerns with July 15 target for launch?

**Comment by clararaubertas** [comment]
How close do you think we are on your/BSS end to completing testing? Are we expecting just a small trickle of minor issues (like those from today), or potentially a lot / more serious fixes?

**Comment by sbxchicago** [comment]
I'm feeding you as many as I can tomorrow. Expect maybe ten more. After that we should stabilize to a trickle. Let me commit to that AFTER I get these out to you.

**Comment by sbxchicago** [comment]
I've been slow. I'll should have remaining clarifications and some new issues to you tomorrow (Wednesday).
