### ISSUE TITLE
Resource listing - Load more shouldn't appear on every listing of resources

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#196]
Remove Load More unless the minimum of resources is included, 25 resources. And Back to Top appears only when Load More appears.

**Comment by clararaubertas** [comment]
I think this needs some back-end/front-end coordination... Erica, what front-end code should go with "Load More"?

**Comment by rockygulliver** [comment]
I've got a placeholder styled, up and running, but not pointing to anything, in some of the template files:

app/views/blog_posts/index.html.erb
app/views/events/index.html.erb
app/views/resources/index.html.erb

Like just needs the class .load-more 

```
    <!-- CONDITIONAL if there are more then display ... -->
    <a class="load-more" href="#">Load More</a>

```

![screen shot 2017-06-20 at 3 40 17 pm](https://user-images.githubusercontent.com/6455077/27354940-f2bbd1fe-55ce-11e7-8166-24f6bf7a99a3.png)

**Comment by clararaubertas** [comment]
Does this need additional code in order to actually load more?
Back-end is just loading all applicable resources right now, but we can change this as needed.

**Comment by rockygulliver** [comment]
Yeah, this'll need additional code to talk to the database/Github actually load more, this is just a placeholder

**Comment by clararaubertas** [comment]
Cool -- I need guidance on what this should do markup-wise and can then implement it.

**Comment by rockygulliver** [comment]
I think I must not be understanding! I thought that current Load More markup is good to go, altho if it helps you to add an id to the <a> it won't impact the styling. 

Like how in this example the Load More button is just

`<a href="#" id="loadMore">Load More</a>
`

https://codepen.io/elmahdim/pen/sGkvH

**Comment by rockygulliver** [comment]
... in that example I sent, it looks they just hide Resources, but I had the sense that the intent on BSSw is to actually dynamically load/populate Resources/Events/Blog posts etc on click

**Comment by clararaubertas** [comment]
Yeah, button is good to go, but I'm not sure how exactly we want to do loading. Sounds like Matt/Brad may have the best guidance here?

**Comment by sbxchicago** [comment]
Let me cover with Brad and respond.

**Comment by sbxchicago** [comment]
This is now covered in BCamp punchlist
