### ISSUE TITLE
announcements md file - no longer by year

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#197]
Lois is considering a single announcement file rather than new one each calendar year as currently indicated. Easy?

**Comment by clararaubertas** [comment]
No change needed! Just needs to match 'Announcements' in filename.

**Comment by sbxchicago** [comment]
I'm looping Lois in. I deleted the 2018 announcement and changed the name of the 2017 announcement to be universal. I think we are still in business. I'm waiting to see if anything brakes in the next commit.

**Comment by clararaubertas** [comment]
Latest commit made/pushed and data imported, looks like we're good!
