### ISSUE TITLE
Announcements file - are display dates having an affect on when these display

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#199]
Files use display dates in an effort to impose a start date and to sunset. Is this wishful thinking or does this work?

**Comment by clararaubertas** [comment]
Yes, this has been implemented.

**Comment by clararaubertas** [comment]
Let me know any problems with this.

**Comment by sbxchicago** [comment]
Cool, we'll test when the time is right.
