### ISSUE TITLE
Blog - need ability to override automatic publish date

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#203]
The blog is posting the actual publish date in the metadata, but BSSw would like the publish date they enter to override that.

**Comment by clararaubertas** [comment]
This should be changed now -- do you have an example of a blog post that has an overriding publish date that we can check?

**Comment by curfman** [comment]
Yep, here you go: 

https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/Articles/Blog/ImproveUserConfidenceInSwUpdates.md

**Comment by clararaubertas** [comment]
Great -- this appears to be working as expected.

**Comment by sbxchicago** [comment]
Problem now is that the override date is displaying in tthe main body copy as a header before the main text begins. Can this be hidden?

**Comment by clararaubertas** [comment]
Should be fixed!
