### ISSUE TITLE
Events - deck should be incoprorated into .md file

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#204]
Events now have a deck. But in the .md file no deck is included. Can these pages function the same way as other pages with a deck with the first paragraph becoming the deck? 

Presuming this is a fix you can make, can you paste the placeholder deck that appears in the display into that position?

**Comment by clararaubertas** [comment]
Can you be more specific about what needs to be changed here? In http://bss.parallactic.com/events, the first paragraph of the text from the page "Events Upcoming" is displayed as a deck.
