### ISSUE TITLE
Activate "Publish: no"

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#205]
The Sample Community is displaying even though  "Publish: no" metadata is in place. BSSw plans on including unpublished content widely — for use as templates for their contributors. Can this function be activated in site content?

**Comment by clararaubertas** [comment]
Should be active already - if this doesn't seem to be working, please let me know examples.

**Comment by clararaubertas** [comment]
Oh whoops, just noticed you cited "Community." Should be active for resources, and I'll get on it for other types.

**Comment by clararaubertas** [comment]
For this to work correctly we will also need "Publish: yes" in the metadata for the communities that are to be displayed.

**Comment by curfman** [comment]
Fixed; commit 5d9dda726a930c1eb850de2eae33cbd398688a3f

**Comment by clararaubertas** [comment]
Ok, this should be working now!
