### ISSUE TITLE
Blog & Events intro text - let’s get rid of it. 

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#207]
This is the text below the deck. 

Lois, I could cut this stuff out easily if you like, but I'm leaving this up to you since you mentioned you might want to put it elsewhere.

**Comment by curfman** [comment]
Done; commit f8cd160925d685cea31dde7707713b6b841a48c7

**Comment by sbxchicago** [comment]
A little text remained on Upcoming and Past Events pages. I removed it. Should be good.
