### ISSUE TITLE
Blog Posts - deck is being autopopulated

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#208]
Blog Posts now have an auto-generated deck. But in the .md file no deck is included. Can the first paragraph become the deck?

**Comment by curfman** [comment]
Added deck placeholder for remaining blog post sample.  Commit b8211ce2c2302fc4ea303b8f4e313ec0ad30521a ... Will adopt format that all blog posts have a deck (1-sentence explanation of blog article topic -- brief and to the point).  

Question: Should regular articles (not just blog articles) have a deck, too?

**Comment by clararaubertas** [comment]
OK, first sentence of blog posts now displayed as deck!

**Comment by clararaubertas** [comment]
Regular articles currently have a placeholder for this -- let me know how you want to handle this.

**Comment by curfman** [comment]
Whatever Matt recommends.

**Comment by sbxchicago** [comment]
2 responses to this issue of autopopulated decks: 

1) I'm not sure what articles we will have outside of Blog posts — none, correct Lois?

- It's kind of an unnecessary distinction and we might avoid future confusion to simply have a Blog folder, though I'm not sure if that puts more work on Clara's plate. Lois can you chime in first? 

2) I'm not sure the advantage of automated placeholder decks (intros) anywhere. I see it is currently being employed in events. And luckily nowhere else. We ALWAYS want the first line of any repeating post type (Blog, Event, Resource) to be promoted to the deck.

- Lois can you confirm? Then we can request from Clara what we need from her.
