### ISSUE TITLE
Add new curated content file: HowToWriteGoodDocumentation.md

### ISSUE THREAD

**Issue by curfman** [betterscientificsoftware/betterscientificsoftware.github.io#23]
Create curated content file, following style of HowToEnablePerformancePortabilityForCseApps.md

**Comment by dmcdougall** [comment]
Happy to pick up the baton here if needed.

**Comment by curfman** [comment]
Hi Damon -- Thanks for volunteering!  Let's start a new issue for details about documentation tools, as discussed during the minisymposium.  That is separate from this curation issue, which is just a pointer and brief description of another doc: https://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-DocumentationHowToWriteGoodDocumentation-V0.1.pdf
