### ISSUE TITLE
Link to "How to contribute" in StyleGuide.md is broken.

### ISSUE THREAD

**Issue by fpnick** [betterscientificsoftware/betterscientificsoftware.github.io#233]
The link points to 

> https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/HowtoContribute.md

whereas it should point to

> https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/HowToContribute.md

(capital 'T' in "HowToContribute")

**Comment by curfman** [comment]
Fixed; thank you, Fabian.
