### ISSUE TITLE
Upcoming Series on Requirements and Requirements Engineering

### ISSUE THREAD

**Issue by rmmilewi** [betterscientificsoftware/betterscientificsoftware.github.io#234]
This is a placeholder issue for an set of articles I have in the works for requirements and requirements engineering. The plan is to split the content into what-is and how-to articles. Hopefully, the content will be rolled out within the next three weeks.

In this article series, we will explore the practical application of requirements engineering for scientific software. We provide terms, tools, and techniques to empower both scientific software developers and clients. Moreover, we give step-by-step examples to illustrate how the requirements phase can be employed, both for small projects intended for a limited audience as well as large-scale, mission-critical codes.

In the how-to section, we illustrate the requirements engineering process with a case study of a hypothetical future software project, LIGRE, a next-generation subsurface modeling code designed to support colonization operations on Mars.

**Comment by rinkug** [comment]
This has been done: https://bssw.io/items/overview-of-requirements-and-requirements-engineering
