### ISSUE TITLE
Possible curated link: Documentation, testing, coverage, and publishing of Julia packages

### ISSUE THREAD

**Issue by ChrisRackauckas** [betterscientificsoftware/betterscientificsoftware.github.io#243]
I am wondering whether you'd accept a curated link to the following blog post:

http://www.stochasticlifestyle.com/finalizing-julia-package-documentation-testing-coverage-publishing/

It's on finishing up the packaging toolchain for Julia, a popular scientific computing programming language. It walks though setting up unit tests, continuous integration, coverage, automatic generation of documentation, and publishing to the package repository.

**Comment by maherou** [comment]
We welcome a submission on this topic.  The current BSSw leadership team does not have an expert in Julia, but we recognize its importance and growing use.

If you want to submit a draft at some point, for more detailed review, please feel free to submit a pull request.

Thank you.

**Comment by ChrisRackauckas** [comment]
Julia's v1.0 with Pkg3 will be coming out soon. Let me write a new post for that and hold out for it to release.

**Comment by maherou** [comment]
Great. Also noticed this posting from NVIDIA 

https://devblogs.nvidia.com/parallelforall/gpu-computing-julia-programming-language/

**Comment by jarrah42** [comment]
The link doesn't work for me.

**Comment by bernhold** [comment]
@jarrah42 same here.  Looks like he may have "rebooted" his blog since the idea was submitted.  We could contact him to see if there is a current alternative.

**Comment by rinkug** [comment]
> @jarrah42 same here. Looks like he may have "rebooted" his blog since the idea was submitted. We could contact him to see if there is a current alternative.

Is anyone following up with him? If not, we should move this as "no interest"? or something else since we seem interested in the topic if not the specific article...

**Comment by rinkug** [comment]
The link seems to work for me now.

**Comment by markcmiller86** [comment]
I down-voted because I would like to avoid articles that focus on a specifc package/product.

**Comment by prwolfe** [comment]
So this issue seems to have gathered a second link from Mike. I looked at both and have very different opinions about them.

I did have some difficulty accessing the blog even with the new link. The original request seems to low-level for this venue focusing as it does on specific packaging needs in Julia, package definitions, licensing requirements, etc. I agree with Mark that this is Julia-only content and have down-voted it.

The second link seems more promising as it focuses more on how Julia can be used in a GPU environment. I am going to read this one again and if I think it is of interest I will open a separate issue to consider it.

Paul

**Comment by jarrah42** [comment]
So is there an EB policy that articles have to be "generic" in some way? Seems like this is more a failing of the site not providing scope for specific content.

**Comment by bernhold** [comment]
I don't think we have an official policy.  I think some individuals on the EB have opinions.  A big part of why we have these discussions about topic proposals is to achieve consensus on what we think the site should be.  To *develop* the policy in other words, whether we write it down or not.

**Comment by markcmiller86** [comment]
So, in re-reviewing...I favor as a CC resource

**Comment by rinkug** [comment]
Is the version of Julia being referenced in article still valid?

**Comment by rinkug** [comment]
PR #443 was created for this topic.This was authored by Marc Miller.
