### ISSUE TITLE
Add new curated content file: GitTutorialAndReferenceCollection.md

### ISSUE THREAD

**Issue by curfman** [betterscientificsoftware/betterscientificsoftware.github.io#25]
Create curated content file, following style of HowToEnablePerformancePortabilityForCseApps.md

**Comment by bartlettroscoe** [comment]
Done on PR #44 an ready to review.  If this does not need a review, then I can just merge.  Just give the word.

**Comment by bartlettroscoe** [comment]
Given that @maherou accepted #44, this is now complete.
