### ISSUE TITLE
Article Idea: Unit Testing of Fundamental Numeric Algorithms

### ISSUE THREAD

**Issue by swoodeng** [betterscientificsoftware/betterscientificsoftware.github.io#250]
Example of how to start a numerical project with unit testing (Catch2).

Online resources (source codes and tutorials) introducing the use of testing to develop and refactor implementations of fundamental algorithms (e.g. Newton-Raphson, Arnoldi, Euler, Runge-Kutta). Fundamental algorithms are chosen to enable a focus on testing and software carpentry within the context of scientific computing.

**Comment by maherou** [comment]
Please proceed with a draft.  If you would like feedback as you develop the content, please let us know.

**Comment by swoodeng** [comment]
Thank you @maherou.  I'll share draft content along the way.

**Comment by rinkug** [comment]
@bernhold to follow up on this (or maybe Mike?)
Question: We already have an article on Catch. Need to check if this article will focus on testing of numerical algorithms or will focus be on Catch?

**Comment by rinkug** [comment]
Lois @curfman to put a relevant link here.

**Comment by markcmiller86** [comment]
We discussed this more on EB telecon... @curfman will add a link to a related article on experiences with Catch2 currently in development.

For a CC article, it would be a bit stronger if we approached this from c++ unit testing tools in general and along with some discussion of Cathc2, we list 2 (or more) others and resources for more information.

**Comment by rinkug** [comment]
Emailed Lois for update on 10/18

**Comment by curfman** [comment]
Article by Mark Dewing: https://bssw.io/items/unit-testing-c-with-catch

**Comment by rinkug** [comment]
This was done and should be closed.
