### ISSUE TITLE
Rename this repository to bssw.io (or similar)

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/betterscientificsoftware.github.io#260]
Following recent discussions with Mike and Lois, I'm proposing that we rename this repository from betterscientificsoftware.github.io to bssw.io (without necessarily changing the parent organization).

The current name was chosen to give the repo a web presence via GitHub Pages. But that's not how it is being used, and I believe potential contributors would find it more logical to look for a repo with the same name as the site they want to contribute to.

This change would have numerous ramifications which would need to be first thought through and then worked through.  A few that come to mind:
1) The bssw.io front-end would need to be reconifgured (hopefully not otherwise changed).  This would need to be coordinated with the repo move
2) The companion images repository might be renamed to something more mnemonic, like bssw.io-images at the same time (in anticipation of other repos appearing under this organization).
3) Content on bssw.io that points to the GitHub repo would need to be updated (e.g., instructions for contributions)

People we specifically need to engage:
* Matt Stone
* Clara Raubertas

Discussion welcome.

**Comment by rinkug** [comment]
@bernhold @curfman : New thoughts on this?

**Comment by bernhold** [comment]
I still think this is desirable, though I don't think it is urgent.

**Comment by bernhold** [comment]
@bartlettroscoe has proposed a new git workflow for the EB to use (issue #330 and PR #436 ).  It would entail directly associating git branches with the production and preview sites.  Which, of course would require reconfiguration of the connection between the server and GitHub.  If we decide to make a change like that, it might be a convenient time to change the repo name, if we decided to.

**Comment by bartlettroscoe** [comment]
I would vote for this making the change.

**Comment by rinkug** [comment]
Please see follow on issue #555
