### ISSUE TITLE
Complete text for 10 common learning myths

### ISSUE THREAD

**Issue by maherou** [betterscientificsoftware/betterscientificsoftware.github.io#262]
@elaineraybourn: Please update this file, then change publish to yes in the meta data.  The content seems to not be complete: https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/MobileTest.md

If this file is not intended for publication, please delete it.

**Comment by jarrah42** [comment]
Personally, I avoid the "10 common...", "15 ways to..", "27 commands you need to know..." etc. style of articles.

**Comment by markcmiller86** [comment]
> But I agree this needs to be completed or deleted.

😕

**Comment by jarrah42** [comment]
> > But I agree this needs to be completed or deleted.
> 
> 😕

Just agreeing with Mike's comment.

**Comment by bartlettroscoe** [comment]
Very general.  I would not expect to find an article like this on the BSSw site.

**Comment by rinkug** [comment]
Closing as it has multiple thumbs down
