### ISSUE TITLE
Develop a style guide for contributors (especially blog articles)

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/betterscientificsoftware.github.io#270]
It would probably be useful to have a style guide for BSSw to offer guidance for what we're looking for in writing style as well as mechanics.

Matt Stone referred us to the guide for A List Apart (http://alistapart.com/about/style-guide) as one reference point.  But this is not exactly suited to our use for various reasons.

**Comment by bernhold** [comment]
Another style guide that Matt likes: https://content-guide.18f.gov/, for reference.  As he notes, it is probably more detailed than we need.

**Comment by rinkug** [comment]
This is under progress..

**Comment by bartlettroscoe** [comment]
Is this not part of PR #510?

**Comment by bernhold** [comment]
Now it is.  Two years ago, when I opened this issue it wasn't.  Closing in favor of PR #510
