### ISSUE TITLE
Content suggestion: Konrad Hinsen blog

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/betterscientificsoftware.github.io#272]
http://blog.khinsen.net/

Konrad Hinsen frequently blogs about software development, engineering, reproducibility and other issues of interest to the BSSw audience.

**Comment by jarrah42** [comment]
I think curated content should be for specific articles, not for blogs or web sites where we don't know what content is posted.

**Comment by bernhold** [comment]
@jarrah42 I think there is value in suggesting people we think of as thought leaders in the community. When I find that such people have a blog that has a fair fraction of software-related content, I will often follow them.

I view Konrad as one such, and can recommend others from my own blog roll.  I was thinking of a cc article per person, or perhaps a single cc article on "thought leader blogs".

**Comment by bernhold** [comment]
As an alternative to one cc article per "interesting" blog, we could have a single "Software Thought Leader Blog Roll" article.  In addition to Konrad's, I owuld include URSSI, BSSw (is that cannibalism?), Dan Katz, http://blog.martinig.ch/, and others may also have suggestions.

**Comment by jarrah42** [comment]
I'd be ok with that.

**Comment by rinkug** [comment]
The "Software Thought Leader Blog Roll" is a good idea if we roll out such series. Otherwise, I agree with Greg about whether we should be putting blogs as curated content...

**Comment by bernhold** [comment]
@rinkug, I don't understand what you mean by "if we roll out such series".  I'm proposing cc article(s) that point to the blogs of people we consider to be worth following -- their blog contains software productivity/sustainability content of sufficient quality and frequency.  As far as I'm concerned, it could be one cc article per worthy blog, or a single cc article that lists them all.

So what does "series" mean in your comment?

**Comment by bernhold** [comment]
To pull in the idea from #5 , we could expand this to web sites that often have useful content, even if they're not exactly a blog.

**Comment by jarrah42** [comment]
To clarify, I'd support a single cc article that provides a list of blogs, not a cc article per blog. I think the latter would be too difficult to keep updated (e.g. if the blog goes away, something inappropriate is posted, etc.) I *would* support the latter if we had finer grained information on articles and could tag them as blogs. See #437 for my suggestions on that topic.

**Comment by rinkug** [comment]
Reopen a new issue since team has narrowed down on a single cc article that provides a list of blogs. We may have to update it regularly.

**Comment by markcmiller86** [comment]
@bernhold will close this and open a new on on the blog roll idea
