### ISSUE TITLE
Curated content suggestions: two journals for software

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/betterscientificsoftware.github.io#273]
Author: Rinku Gupta (@rinkug)

http://sjscience.org/about-sjs
http://rescience.github.io/

**Comment by rinkug** [comment]
From Lois: Would these fit as additions to the list of journals we have in the curated content somewhere on bssw already. @rinkug to check

**Comment by rinkug** [comment]
This is an easy addition to the list. We need a short  introductory paragraph for the two journals. I can do  this  one.

**Comment by rinkug** [comment]
A PR has been created for this item. Discussion will be continued on the PR #427
