### ISSUE TITLE
Article "Best Practices for Scientific Computing" by Greg Wilson

### ISSUE THREAD

**Issue by pagrubel** [betterscientificsoftware/betterscientificsoftware.github.io#277]
This article has merit for anyone who wants some quick guidelines to follow for best practices. The article has a good summary so those short on time can skip to things they are very interested in. Its a good beginning for anyone who wants to implement best practices whether a manager, computer scientist or domain scientist. I think this article fits well for the site. 

http://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1001745

**Comment by maherou** [comment]
@pagrubel: Do you want this content added as a curated article?  If so, and you are interested in providing the contribution yourself, you could submit it using our new Google Form submission.  See instructions in the README file: https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/README.md

**Comment by pagrubel** [comment]
@maherou I'm in the process of doing that and seeing how that works out too. I'll send comments if once done

**Comment by pagrubel** [comment]
@maherou I tried using the form and got stuck at accepting the license even though I selected yes. Also, it might be more esthetic to see a markdown output of the license instead of numbered lines, but that's not as important as being able to continue.

**Comment by maherou** [comment]
@pagrubel, Make sure you select yes to both questions on that page.  I have added some helper text to each. Can you check if that was the issue?

You need to select "yes" to:

I have read these guidelines and want to contribute.

and

I agree to the licensing terms (MIT license) described here: https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/LICENSE

**Comment by pagrubel** [comment]
@maherou @curfman I do have a few comments on using the form. Where should I send them. Also, I did submit the content and was wondering where that ends up.

**Comment by maherou** [comment]
@pagrubel, I have converted your article to MD.  It is prepared to go live and will be on bass.io after the next upload.  Here is a link:

https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/GrubelBestPracticesSSW.md

Please create a new issue for any suggestions you have.  Assign it to me.

I am closing this issue.
