### ISSUE TITLE
Add new curated links file: Ways to publish your software

### ISSUE THREAD

**Issue by ibaned** [betterscientificsoftware/betterscientificsoftware.github.io#28]
This page, or aggregate page, would contain curated links to journals and similar mechanisms for making your software citable as academic literature and getting citation-based credit for scientific software development. A preliminary list of options follows, whose descriptions may need improvement by people who are more familiar with each journal:

- [TOMS](http://toms.acm.org) (ACM Transactions on Mathematical Software): This is a well-established journal whose articles often describe novel algorithms and their implementation as mature, usable software products. It has also pioneered policies to improve the reproducibility of published research.
 - [TOMACS](http://tomacs.acm.org/about.cfm) (ACM Transactions on Modeling and Computer Simulation): Another well-established journal, which deals more with applications, their impact and results, as well as their methodology (e.g. Verification & Validation).
 - [JSS](https://www.jstatsoft.org/index) (Journal of Statistical Software): Like TOMS, but with a focus on software which implements statistical methods rather than other mathematical modeling topics.
 - [SoftwareX](https://www.journals.elsevier.com/softwarex/): An Elsevier journal which aims to ensure software is cited and gets credit in the literature. This journal accepts submissions regarding software that is used in any of a wide range of disciplines, from mathematics to the sciences and humanities.
 - [JOSS](http://joss.theoj.org) (The Journal of Open Source Software): This journal provides authors with a DOI for their software package without requiring a full-length manuscript. Instead, authors must demonstrate (via a form of peer review) that their package follows certain best practices of open-source software, including proper licensing and documentation, and helps meet scientific research challenges.
 - [Zenodo](https://zenodo.org): Like JOSS, Zenodo can provide a DOI for your software. Unlike JOSS, it does not require a review of the software, and can generate a DOI for each release of your package via GitHub integration. Zenodo also allows users to upload data, and obtain a DOI for their data, while also acting as a hosting/distribution platform for others to access that data.

**Comment by maherou** [comment]
Hi Dan,

This is a good topic.  I would add to your list the Archive of Numerical Software (ANS).  I think a short article on this topic, with links to services listed would be very useful.

If you want assistance,  you could consider starting the document as a Google Doc and ask for collaborators to help write content, or provide comments.  We have an established process collaborative Google doc creation that works well.

**Comment by ibaned** [comment]
I've begun a draft here and the following link should allow comments:

https://docs.google.com/document/d/1PcNfI-v4MkBYQ4GOGTWR_qwaehfRpXWphhVPKaR6m1A/edit?usp=sharing

**Comment by ibaned** [comment]
I have created PR #46 with the new short article. @maherou I received an invitation to collaborate and I thought I accepted it but don't have push access to this repository. Anyway, the PR is there.

**Comment by ibaned** [comment]
Since #46 was merged, I think this can be closed.
