### ISSUE TITLE
Broken link to 'What is CSE Software Testing"

### ISSUE THREAD

**Issue by markdewing** [betterscientificsoftware/betterscientificsoftware.github.io#283]
Under Find Resources->Better Reliability -> See Resources: Testing, one of the topics is "What is CSE Software Testing?". 
Clicking on the link displays a 'not found' page (link address is https://bssw.io/what_is/what-is-cse-software-testing )

The article appears to be available in the repository under CuratedContents/WhatIsCseSwTesting.md

**Comment by bernhold** [comment]
Thanks Mark.  I see the same problem.  Nothing jumps out at me in the md source.

@clararaubertas, do you see anything in the logs?

**Comment by marwahaha** [comment]
Seems to be working now!
https://bssw.io/what_is/what-is-cse-software-testing

**Comment by maherou** [comment]
Closing since the link seems to work.
