### ISSUE TITLE
Blog Article: Adopting Continuous Integration for Long-timescale Materials Simulation

### ISSUE THREAD

**Issue by rjzamora** [betterscientificsoftware/betterscientificsoftware.github.io#293]
The proposed blog article highlights a valuable collaboration between the IDEAS and EXAALT ECP project teams.  The goal of the collaboration was to help the EXAALT team adopt productive and sustainable software practices (with an emphasis on Continuous integration and Testing). 

A draft of the article can be found at: https://github.com/rjzamora/ci-blog

**Comment by curfman** [comment]
Hi Rick -- Looks great; please transition into the BSSw blog area and then we'll move ahead with image treatment and copy edits.

blog area of repo:
https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/tree/master/Articles/Blog

sample skeleton file for blog article:
https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/Articles/Blog/BlogArticleSkeletonA.md

Many thanks,
Lois

**Comment by rinkug** [comment]
This is done: https://bssw.io/blog_posts/adopting-continuous-integration-for-long-timescale-materials-simulation
