### ISSUE TITLE
Using "docker" or other container technology for research software

### ISSUE THREAD

**Issue by chrisrichardson** [betterscientificsoftware/betterscientificsoftware.github.io#30]
We've been using docker/containers for quite a while now, and it is very good at encapsulating complex packages with their dependencies, for use on any Linux/x86 system. Also can be used for continuous integration/automated testing, and will be important for HPC too. 

I could write an article, if it would be useful.

**Comment by dmcdougall** [comment]
> will be important for HPC too

Correct me if I'm wrong, but isn't it the case that a lot of (at least NSF funded) compute clusters don't support virtualisation?

**Comment by chrisrichardson** [comment]
I wrote "will be" important. Certainly, it is still at an early stage, but I expect to see an explosion of interest this year. I have had experience of running on DoE Cray machines with 'shifter', and 'singularity' seems to now also becoming popular. Probably, we will expect to create a 'live' document which will update to reflect the reality as it changes...

**Comment by dmcdougall** [comment]
Perfect.  Thanks for clarifying.

**Comment by maherou** [comment]
Chris,

Please proceed.  This is an important topic.

Thanks.

**Comment by pagrubel** [comment]
Would you include charliecloud? The newest release has unprivledge builds as well on HPC machines

**Comment by rinkug** [comment]
This is done
