### ISSUE TITLE
Programming Languages and Tools appears twice

### ISSUE THREAD

**Issue by jarrah42** [betterscientificsoftware/betterscientificsoftware.github.io#323]
The Programming Languages and Tools topic appears twice on the Better Development page.

**Comment by curfman** [comment]
@clararaubertas Clara -- The Github file lists this topic just once, but it appears twice on the frontend.  Can you help?

See: https://bssw.io/categories/better-development 

https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/Site/Categories/Development.md 

Thanks.

**Comment by clararaubertas** [comment]
This should be fixed now!

**Comment by curfman** [comment]
thanks, Clara.
