### ISSUE TITLE
Add curated article on How to submit a pull request

### ISSUE THREAD

**Issue by maherou** [betterscientificsoftware/betterscientificsoftware.github.io#325]
Add a curated link to this article: https://medium.freecodecamp.org/how-to-submit-a-pull-request-529efe82eea5

**Comment by maherou** [comment]
I have added the article at https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/IntroToPullRequests.md 
@rinkug, If you have time, please review it and make any changes directly and close this issue.  If you don't have time, that is fine.  Just respond in the issue and close it.

**Comment by jarrah42** [comment]
Has this issue been addressed now? I took a look at the article and it seems clear to me.

**Comment by bernhold** [comment]
Agreed
