### ISSUE TITLE
Blog post about a complicated GitHub migration (LLNL team)

### ISSUE THREAD

**Issue by hauten** [betterscientificsoftware/betterscientificsoftware.github.io#326]
[The Great Migration: VisIt Moves from Subversion to GitHub](https://computation.llnl.gov/newsroom/great-migration-visit-moves-subversion-github)

Summary: Migrating 2 million lines of code is easier said than done. Go behind the scenes as an LLNL team discusses the logistics, challenges, and benefits of a complicated move to GitHub.

I support an LLNL development team who recently migrated the large VisIt code base to GitHub (https://github.com/visit-dav/visit). We are interested in submitting a blog post to this site, re: the criterion of “Characterization of challenges and solutions that may be particularly valuable to the CSE community.” It would be a first-person version of the article linked above, bylined by one or more people on the dev team.

We have a chart that shows where the different components were migrated from/to. **Do you want this info presented a table in the Google Doc or as a .jpg?** We have a couple of other images, though the chart is the most important.

Please note: LLNL content posted for an external audience must include an auspice statement and release number. We will include this text at the end.

Thanks for your consideration.
CC @markcmiller86

**Comment by markcmiller86** [comment]
Thanks @hauten for submitting this issue and for the work on the article @ LLNL.

I will mention two broad stylistic adjustments that I think will help place position this content for a BSSw.io blog article.

- Length: we will likely cut down to < 500 words. I can help with that
- VisIt focus: it will likely be useful to cast the description more along the lines of being *an example*  of a migration of a large and enduring project from SVN to GitHub and less on VisIt specifically.

After seeing your article go live earlier today @ LLNL, I started thinking about how to do that

A sligth adjustment in the title..."A Great Migration: how to migrate 2 million lines of source and 20 years of development history from SVN to GitHub"

Anyways, let me know how I can help you here.

**Comment by curfman** [comment]
Terrific topic, @hauten ... I concur with Mark's suggestions.  A draft by say March 25 would provide time for copy edits and image treatment and then releasing on the BSSw site in early April.  Does that timeline work for you?  More info:

- Blog articles appear here: https://bssw.io/blog_posts … and also are announced on the BSSw email digest (monthly).
- Length: General guidance is 250-500 words, though this is flexible (some articles have been shorter, some a bit longer).  

Here is the location in the Github repo:
https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/tree/master/Articles/Blog

Here is a starting point skeleton file (which you could copy and then customize):

https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/Articles/Blog/BlogArticleSkeletonA.md

Thanks; we'd be glad to address any questions.

**Comment by hauten** [comment]
March 25 sounds reasonable. Thanks!

**Comment by hauten** [comment]
@curfman, apologies but we will not be making the March 25 target after all. I'll let you know as soon as our review & release process draws to a close so you'll know when to expect the article.

When it's ready, do you want me to attach the image file to this issue?

**Comment by curfman** [comment]
Thanks for the update, @hauten ... you could provide a pointer to the image(s) that you want to use (if these are online someplace already), and then we'll work on image treatment as a next step.

**Comment by markcmiller86** [comment]
Ok, I've put a draft up, betterscientificsoftware.github.io/Articles/Blog/TheGreatMigration.md

hero image is probably wrong...should probably be front page of VisIt project on GitHub or maybe a pic of an actual bunch of animals migrating ;)

Its too long too and probably some details not useful.

@bartlettroscoe ... would appreciate feedback from you on value of info here.

**Comment by bartlettroscoe** [comment]
@markcmiller86 said:

> @bartlettroscoe ... would appreciate feedback from you on value of info here.

I will take a look and add comments in this issue.

**Comment by bartlettroscoe** [comment]
@markcmiller86 and others,

Quick question, if this is still in review, how can it already be on the master branch:

* https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/Articles/Blog/TheGreatMigration.md

?

Should this not be on a topic branch in Mark's fork of this github repo?

**Comment by markcmiller86** [comment]
First, the master here isn't what is actually on the published site. Its not a normal GitHub gh-pages site.

Next, I followed procedure I've used in a previous draft post as it seemed the branch and PR process then just complicated things.

That said, if pref. is to back out and do via PR, happy to do so.

**Comment by bartlettroscoe** [comment]
@markcmiller86 the problems is that if you don't do a PR, then you can't do a supported code review (or text review in this case).

**Comment by markcmiller86** [comment]
Ok, will remove from master and put into a PR.

Note, this does complicate image links due to fact images are maintained in a sep. repo.

**Comment by markcmiller86** [comment]
Ok, two PRs submitted
* [images](https://github.com/betterscientificsoftware/images/pull/3) 
* article, #329

**Comment by bartlettroscoe** [comment]
@markcmiller86 said:

As for the document itself, the text so far looks good.  I see you have some more to add before this is finished so I can review again once it is finished.

My initial impression is that other than comprehensive usage of git-lfs for every binary file (which I applaud VisIt for using, it is a great tool) the conversion from SVN to git looks pretty standard.  You might mention the tool you used and a link for it.  Also, I am curious about why binary files are being stored in the same git repo and 'master' branch as source.  What workflows/release-models does that support?  That might be interesting to mention in the document because it seems pretty non-standard.  (But if you want to store binaries in the same repo some projects use a different branch in the repo for that so that it does not clutter up the main development branches.)

I am interested in how the migration from redmine to GitHub issues was performed.  Is there a tool to help with that or was that a manual process?  Either way, that is an interesting detail to mention.

I poked around the Visit github repo and make some comments in the expandable section below.   Petty interesting.

<details>
<summary><b>Inspection/analysis of the converted VisIt GitHub repo (click to expand)</b></summary>
.

The new visit github repo is at:

* https://github.com/visit-dav/visit

I cloned the repo with:

```
$ time git clone git@github.com:visit-dav/visit.git
Cloning into 'visit'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 370209 (delta 0), reused 1 (delta 0), pack-reused 370201
Receiving objects: 100% (370209/370209), 263.45 MiB | 38.64 MiB/s, done.
Resolving deltas: 100% (285227/285227), done.
Checking out files: 100% (17993/17993), done.

real    0m16.854s
user    0m14.798s
sys     0m3.786s
```

And the visit repo is not too big at under 1/2 a GB:

```
$ du -sh visit
553M    visit
```

(The Trilinos git repo is over 1.5 GB due to some fat we could not get out of the filter when we moved to github from CVS.)

It currently has 4886 git-lfs reference files:

```
$ find . -name "*7z" | wc -l
84
```

out of a total number of files:

```
$ find . -type f | wc -l
17925
```

Looks like the really used git-lfs for a lot of file formats from looking at:

```
$ cat .gitattributes
data/*.h5nimrod filter=lfs diff=lfs merge=lfs -text
data/*.pdb filter=lfs diff=lfs merge=lfs -text
data/*.dat filter=lfs diff=lfs merge=lfs -text
test/**/*.png filter=lfs diff=lfs merge=lfs -text
test/**/*.tif filter=lfs diff=lfs merge=lfs -text
test/**/*.jpg filter=lfs diff=lfs merge=lfs -text
test/**/*.jpeg filter=lfs diff=lfs merge=lfs -text
docs/**/*.png filter=lfs diff=lfs merge=lfs -text
docs/**/*.jpg filter=lfs diff=lfs merge=lfs -text
docs/**/*.tif filter=lfs diff=lfs merge=lfs -text
docs/**/*.fm filter=lfs diff=lfs merge=lfs -text
*.xyz filter=lfs diff=lfs merge=lfs -text
*.tar filter=lfs diff=lfs merge=lfs -text
*.gz filter=lfs diff=lfs merge=lfs -text
*.tgz filter=lfs diff=lfs merge=lfs -text
*.7z filter=lfs diff=lfs merge=lfs -text
*.zip filter=lfs diff=lfs merge=lfs -text
*.bz2 filter=lfs diff=lfs merge=lfs -text
*.mpeg filter=lfs diff=lfs merge=lfs -text
*.mp4 filter=lfs diff=lfs merge=lfs -text
*.mov filter=lfs diff=lfs merge=lfs -text
*.ppt filter=lfs diff=lfs merge=lfs -text
*.pptx filter=lfs diff=lfs merge=lfs -text
*.pdf filter=lfs diff=lfs merge=lfs -text
*.doc filter=lfs diff=lfs merge=lfs -text
*.docx filter=lfs diff=lfs merge=lfs -text
*.dylib filter=lfs diff=lfs merge=lfs -text
*.dll filter=lfs diff=lfs merge=lfs -text
*.so filter=lfs diff=lfs merge=lfs -text
docs/SphynxDocs/**/*.png text -filter -merge -diff
```

Wow, that is alot of binary file formats!

Note they used git-lfs for even for document files like *.pdf, *.doc, *.docx, etc. 

There are some other interesting files being versioned here like binary libraries *.so, *.dll, and *.dylib.  Why would one put binaries in a git source repo?  What is the workflow that supports?  With git-lfs it can do it but I am just wondering why.

What happens if you actually have git-lfs and it clones all of these files by default?

I went ahead and did:

```
$ git lfs pull
Git LFS: (4116 of 4116 files) 1.59 GB / 1.59 GB
```

That increased the repo size to 4.5GB:

```
$ du -sh .
5.5G    .
```

</details>

**Comment by markcmiller86** [comment]
> the conversion from SVN to git looks pretty standard.

So, that suggests I've probably not characterized things very well. It is/was def. *not* standard. We hand-coded these scripts over weeks of testing to get this right. There are/were no tools to do it for us. For example, look at all the *releases* there in GitHub. Those were just tags in SVN on our release candidate branches for each minor version series (e.g. 2.10.x, 2.11.x, etc.). To make those appear on GitHub as true GitHub releases is a major pain to get right. I dunno the details, just conveying what I learned from others who did the work.

**Comment by markcmiller86** [comment]
On other thing...we've got conversation here now and in the PR. If the major rationale for PRs is having a place to have a conversation about the content, why are we continuing this discussion here in the issue?

Maybe the correct workflow is to converse in the issue *prior* to any associated PR. But, once a PR is submitted, refer to the PR in the issue, close the issue and refer to the issue from PR and continue all subsequent conversation in the PR thereafter?

**Comment by bartlettroscoe** [comment]
There should be a new GitHub issue for the discussion of the contribution workflow.

**Comment by markcmiller86** [comment]
A variant of this was completed with [this work](https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/bca2e90df6bfa95caf559958457227fc640b128d/Articles/Blog/ContinuousTechnologyRefreshment.md) which appears to have happened directly on master :(

**Comment by rinkug** [comment]
Published at https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/Articles/Blog/ContinuousTechnologyRefreshment.md

**Comment by rinkug** [comment]
PR for this issue was #329.
