### ISSUE TITLE
Write curated article on 10 Git Commands you should know

### ISSUE THREAD

**Issue by maherou** [betterscientificsoftware/betterscientificsoftware.github.io#328]
https://towardsdatascience.com/10-git-commands-you-should-know-df54bea1595c

**Comment by maherou** [comment]
@rinkug, @jarrah42, If you have a chance, please review this file: https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/TenGitCommandsYouShouldKnow.md

I have committed it for publication, so it will be posted, but I would appreciate your review before closing the issue.

**Comment by rinkug** [comment]
This is a good article. Thanks for curating this. Would it be helpful in summary to mention that this somewhat geared towards people who are already a bit familiar with git?

**Comment by jarrah42** [comment]
Yes, it looks good to me also.

**Comment by maherou** [comment]
I looked at adding a comment as suggested by Rinku (to mention that some familiarity might be useful), but I think the article can be helpful even then.  For example, the coaching step for getting through a vim session is one of the first things someone might run into. 

I will close the issue and consider the article done.

**Comment by rinkug** [comment]
Published at: https://bssw.io/items/exploring-the-most-useful-git-commands
