### ISSUE TITLE
Blog article by Glenn Hammond on PFLOTRAN's use of CI testing

### ISSUE THREAD

**Issue by curfman** [betterscientificsoftware/betterscientificsoftware.github.io#338]
Blog based on Glenn's poster at the SIAM CSE19 conference.  We've already discussed and Glenn has written a draft.  We'll experiment with using the issue board.

**Comment by curfman** [comment]
Many thanks, Glenn.  We'll next work on image treatment, feedback from a few people, and a pass by our technical editor.

**Comment by rinkug** [comment]
This was already published, correct? Is this the one: https://bssw.io/blog_posts/streamlining-software-development-through-continuous-integration

 @curfman  - please confirm

**Comment by curfman** [comment]
done in spring 2019
