### ISSUE TITLE
Add curated content: tools for software documentation

### ISSUE THREAD

**Issue by curfman** [betterscientificsoftware/betterscientificsoftware.github.io#34]
The topic of tools for software documentation came up during discussion in the CSE17 minisymposium on _[How to Succeed with Open Source Software](http://meetings.siam.org/sess/dsp_programsess.cfm?SESSIONCODE=61149)_, organized by Brian Adams and Damon McDougall.  Damon kindly volunteered to spearhead curating content on this topic.  Thanks, Damon!

Let's try doing this as an 'aggregate' resource to facilitate input of content by multiple people on subtopics, if needed.

**Comment by dmcdougall** [comment]
No problem!

I'm stoked to contribute.  I have a paper deadline on Monday but should be good after that.

**Comment by dmcdougall** [comment]
Fixed in #61.  Feel free to close this issue.

**Comment by pagrubel** [comment]
Done
