### ISSUE TITLE
Create some issue templates; hand off to Pat G.

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/betterscientificsoftware.github.io#342]
I've created some issue templates. You can stumble into them if you try to submit a new issue.

I also created [this video](https://youtu.be/Dy7isHImrAM) to help explain how to create/edit them.

I don't like how the template kinda sorta blurs instruction with the actual submission but don't know what to do about that either.

Feel free to close this issue if after review the templates and/or the video, you have sufficient info to proceed.

**Comment by markcmiller86** [comment]
So, I already see something that doesn't work too well with the curated content template. The checkboxes work fine...as long as they are not deleted as part of the submission. Maybe Mike's idea of using the thumbs up emoticon (restricted to the original issue submission and not burried down in the follow-on conversation) would work better. One thing I do like about the check-box approach is that the status of those check-marks appears in the issue as (0 of 2 tasks completed) so its easy to review a page full of issues and see which have already recieved two favorable reviews.

**Comment by markcmiller86** [comment]
BTW...sorry if the video quality isn't great. I chose to store in 480p due to size. I think its sufficient to see your way around the repo.

**Comment by pagrubel** [comment]
Nice video Mark, but I don’t have access to settings anymore. I did figure out how to unassign myself by editing the template file directly.

**Comment by markcmiller86** [comment]
> Nice video Mark, but I don’t have access to settings anymore. I did figure out how to unassign myself by editing the template file directly.

Sorry. Hadn't realized I was utilizing *magic powers* to go through the GitHub web interface to edit the templates. Hmmm... Sounds like you did find how to do it directly by adjusting YAML front-matter in the TEMPLATE files in the repo. That works too. In fact, going through GitHub web interface does the same thing in terms of doing git operations on the repo.

**Comment by pagrubel** [comment]
I really think I was able to do it earlier, but I won’t guarantee my memory is correct.
