### ISSUE TITLE
Rinku Trying sample issue

### ISSUE THREAD

**Issue by rinkug** [betterscientificsoftware/betterscientificsoftware.github.io#350]
Test the following
1. Assign a reviewer - works fine

2. Can I assign it to a project board - this actually works fine. If I select a project-board from the right hand side column on this page, the issue gets reflected on the correct project board. The project boards can have many lists: for ex: the curated-content-ideas board has lists named as idea-backlog, topic-review, idea-development etc. I dont think we can choose "what list"  in the project board it goes into, it perhaps gets loaded into the first list (idea-backlog) or perhaps the project-board has a default list setting.

3. Write two comments and hide one - works fine

4. How can reviewers indicate that they are done reviewing this item? Any option for this on this issue page?

5. How do publish this item on bssw.io?

6. How to notify submitter that item has been accepted or rejected? Any way to do  from this page?

**Comment by rinkug** [comment]
This is unhidden comment

**Comment by rinkug** [comment]
Can I hide this comment?

**Comment by pagrubel** [comment]
So its hidden but I can see it if I click on it. I'm wondering if only someone who is part of the project can see the comment?

**Comment by markcmiller86** [comment]
Yes, only someone part of the project can view hidden stuff. To test, log out of GitHub or go to it from a different browser you haven't logged into GitHub (recently) with. I recall testing and reporting on this a couple of months ago.

**Comment by rinkug** [comment]
Yes, I doublechecked this yesterday when I logged out and its hidden, so its works just fine.

Rinku

On 5/3/19 11:17 AM, Mark C. Miller wrote:

Yes, only someone part of the project can view hidden stuff. To test, log out of GitHub or go to it from a different browser you haven't logged into GitHub (recently) with. I recall testing and reporting on this a couple of months ago.

**Comment by markcmiller86** [comment]
Closing this as it is just a sample
