### ISSUE TITLE
4 year old blog post on HPC and MPI vs. Big Data and Spark/Hadoop

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/betterscientificsoftware.github.io#353]
This topic has been discussed a lot over the past several years.

I ran across [this 4 year old blog post](https://www.dursi.ca/post/hpc-is-dying-and-mpi-is-killing-it.html) and decided to read it. Having some experience with Spark and Hadoop, I kinda agree with several of its rantings. I found the [26 comments](https://disqus.com/home/discussion/ljdursi/hpc_is_dying_and_mpi_is_killing_it/) particularly interesting.

I don't honestly know if this is the best/fairst treatment of this topic available but wanted to ask if others could take a look and give it a thumbs up or down as possible curated content.

**Comment by bernhold** [comment]
It is an interesting discussion, no matter which side you're on.  But is this just an HPC thing?  Or is the productivity/sustainability angle here strong enough for BSSw?  I'm not sure.

**Comment by rinkug** [comment]
This was closed due to lack of interest
