### ISSUE TITLE
Career Software Productivity and Simple Ergonomics Considerations

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/betterscientificsoftware.github.io#36]
I would like to add a How-To on simple ergonomics adjustments and health related exercises to fend off negative health effects of sitting for hours in front of a computer screen day after day, year after year as part of a career in software development.

**Comment by markcmiller86** [comment]
I am not able to set labels, assignees projects or milestones. I suspect I don't have write permission to this repo?

**Comment by markcmiller86** [comment]
Here is a bulleted list of items

- Motivation
  - If you're going to be developing software as part of your career, you are likely to eventual face questions about eye health, overall fitness, etc. This article gives some simple things you can do aimed at minimizing negative impacts of...
- Negative impacts
   - Sitting for long periods and impact on body fitnes, posture, weight gain
   - Looking at computer screens for long periods and impact on vision
- Eye health
  - Soloraize color scheme
  - Research about light text on dark bachground and vice versa
  - font (size and shape)
  - eye exercises and computer glasses
- Body health
   - research on sit/stand paradigms and some simple desk options
   - apps that help remind you to get up and move around
   - simple exercises that help

**Comment by curfman** [comment]
Hi Mark -- Good ergonomics are indeed important for sustainable and productive scientific software careers.  An article with pointers to resources would be very useful.  Please proceed.  Thanks.

**Comment by markcmiller86** [comment]
I reduced scope from all ergo to just eye/vision health. 

https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/Articles/VisionFitnessForSoftwareProductivity.md

There is a tag/metadata block in comments on this page that still needs work

**Comment by gonsie** [comment]
Hi Mark,
Great idea and article! You should also mention font size, larger is better 😄

**Comment by apieum** [comment]
I would suggest a word about pomodoro, and how it's hard to recover from a long moment of concentration instead of taking pauses (where you can stand up...).
https://youtu.be/IlU-zDU6aQ0

**Comment by markcmiller86** [comment]
Ok, I made some edits for above recommendations
