### ISSUE TITLE
"When is it better not to write automated tests?" Blog article

### ISSUE THREAD

**Issue by bartlettroscoe** [betterscientificsoftware/betterscientificsoftware.github.io#360]
CC: @curfman, @maherou, @bernhold 

I have written a draft for a short blog article "When is it better not to write automated tests?".  I will have to send it through SNL R&A before I can post it here but I can send a draft to people offline in email to take a look at first.

I feel this goes with #331 "Working Effectively with Legacy Code" very nicely.

If interested, I will send out a draft of the formatted article.

**Comment by markcmiller86** [comment]
I wonder if it makes sense to shorten #331 quite a bit and use the tandem blog article to capture what you do not include in #331 and, of course, with a link from the curated content article to this tandem blog article.

**Comment by bartlettroscoe** [comment]
In my opinion, a blog article should have mostly unique material.  The material in this PR branch is really just a very short summary of existing material in the book "Working Effectively with Legacy Code".  Think of it as an extremely short Cliff Notes for "Working Effectively with Legacy Code".  Can there be some variability in curated content to allow this?

**Comment by curfman** [comment]
In my view, this material would be a good fit for either curated content or an article (distinct from a blog article).  The boundary between the 2 is somewhat fuzzy (lengthier content generally in articles, though to date there have been just a few); the resource would appear the same on the frontend regardless (as a 'resource') rather than blog.

**Comment by bartlettroscoe** [comment]
FYI: I submitted a draft to the SNL R&A process and I sent a draft to @curfman, @bernhold, @maherou, @elaineraybourn, and @markcmiller86 to get some preliminary feedback.  Once this is approved by SNL for release, I will post a PR if there is interest.

**Comment by bartlettroscoe** [comment]
Comment from @curfman below.

Once I post the PR, I can add some section headings to break this up some to make it easier to browse.

---

Hi Ross – Thanks for proposing this article and writing a complete draft.  I believe this would be a very nice BSSw blog article as a complement to your other resource about the Feathers book.  I am sure that others who are considering strategies for expanded testing would benefit from considering these issues.

From a stylistic point of view, I recommend inserting a few subheadings to guide the reader.  We could schedule this to appear in late June or July.

Others may have additional comments about content.  

Best,
Lois

**Comment by rinkug** [comment]
> In my view, this material would be a good fit for either curated content or an article (distinct from a blog article). The boundary between the 2 is somewhat fuzzy (lengthier content generally in articles, though to date there have been just a few); the resource would appear the same on the frontend regardless (as a 'resource') rather than blog.

Is length the only criteria for distinguishing between articles and blogs, right now?

**Comment by curfman** [comment]
The wording in my comment above was not clear.  Please see [WhatToContribute.md](https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/WhatToContribute.md) for a description of content types.  In particular:

- Curated links: A brief article that highlights other web-based articles or content. Your article should describe why the CSE community might find value in the linked content.

- Original experience: An original article to inform the CSE community about how to improve developer productivity and software sustainability.

- Blog article: An original article in the form of a blog of 250 - 500 words. We will solicit contributions from thought leaders in the community and welcome proposals from anyone.

The distinction with length is really contrasting between curated content (tends to be short, mostly framing external content) and an original experience article (tends to be somewhat longer than curated content, in the same length range as blog articles).

**Comment by bernhold** [comment]
I do *not* have a crisp definition for what distinguishes original articles and blogs. But it is not length.

Generally, I think of blogs as more like op-ed pieces in newspapers, and original articles as being more like regular newspaper articles – more factual or analytical.  That’s not crisp in part because I think thoughtfully constructed reviews (I don’t think we want to be endorsing one product over another, but I think it is useful to offer comparisons based on clearly articulated criteria) and extended experience reports would make good original articles too.  Also, I think that the WhatIs and HowTo documents, when we resurrect those, would fall in the original article category.  And personally, when I write blog articles, I often use a more informal style of writing than I would consider appropriate for an original article.

But that’s just my opinion. I think this should be discussed among the editorial board, eventually.

**Comment by bartlettroscoe** [comment]
@curfman said:

> Blog article: An original article in the form of a blog of 250 - 500 words. We will solicit contributions from thought leaders in the community and welcome proposals from anyone.

Just doing a rough word-count on the existing articles in the directory Articles/Blog/:

```
$ cd Articles/Blog/

$ find . -name "*.md" -exec wc -w {} \; | sort -rn 

4157 ./ReferencesInMarkdown.md
2398 ./ApolloGuidanceComputerPart1-wikized.md
1992 ./SoftwareAsCraft.md
1702 ./ApolloGuidanceComputerPart1.md
1570 ./OnDemandLearningForBetterScientificSoftware.md
1443 ./GinkgoSustainableSoftwareInAnAcademicEnvironment.md
1226 ./2018-11-messer-porting.md
1178 ./AdoptingCIforEXAALT.md
1164 ./ContinuousTechnologyRefreshment.md
1152 ./OutreachForBSSw.md
1150 ./SCSoftwareConference.md
1132 ./ScalingSmallTeamsToATeamOfTeams.md
...
```

But that includes meta-data and everything. 

The current draft of my blog article "When is it better not to write automated tests?" is:

```
$ wc -w 2019-05-17-when-is-it-better-not-to-write-tests.md
1409 2019-05-17-when-is-it-better-not-to-write-tests.md
```

All of the meta-data is not there yet (I debugged this in my local jekyll github.io site so that I could render the markdown locally) but this looks to be within the range of several of the other published blog articles (and we can cut down my mine as well to fit any length desired).

**Comment by bernhold** [comment]
I agree with Lois in that Curated Content should be short, and simple to write and review.

I can easily envision original articles longer than the 250-500 words we say for blog articles in some cases. (I wonder if anyone’s actually analyzed our real blog articles?)

**Comment by bartlettroscoe** [comment]
I guess we should just wait until I can post the PR with the actual proposed content (originally targeted as a blog) and then someone can decide which is the best format.

But note that the BSSw.io site calls out new blog articles at the top of every page which it does not do for other types of new content.  That seems to raise the prestige/importance of blog articles compared to other types of content on the site (which is likely to go unnoticed).

**Comment by markcmiller86** [comment]
> 4157 ./ReferencesInMarkdown.md

That file wasn't an actual Blog Post. It was example and instructions on how to us GitHub Flavored Markdown (GFM) to achieve Wiki-pedia style footnoting and references list. I put it here because it pertains to the blog but should really be in another place where we keep adminstrative materials.

**Comment by elaineraybourn** [comment]
I like the transparency of your blog. You share how you have struggled with decisions, gained insights from a thought leader, and made changes accordingly in your thinking. I believe there are other readers who will have been in your position, and will appreciate that you are courageous to share your struggles, and that your thinking changed after accessing a resource, and thinking further.

When I read your blog, I was interested and had many more questions. I think your blog would be strengthened with examples (if possible) and definitions of terms. For example, what is the validation-centric approach? What in the book was the tipping point to change your thinking? How did this perspective apply to your code? What changes did you make? Now that you know this, how has this changed the way you think and conduct testing?

As you flesh out the blog, think about telling the reader a story about your journey with details so they can “replicate it,” if needed. I think you are almost there with a few more details.

**Comment by bartlettroscoe** [comment]
FYI: The draft passed SNL R&A so I can post a PR here with the draft article "When is it better not to write automated tests?"

**Comment by bartlettroscoe** [comment]
This was approved to get worked, yes?  Can one more "thumbs up" on the initial comment [above](https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/issues/360#issue-446173609)?

**Comment by bartlettroscoe** [comment]
Looks like we have 4 thumbs up now so I moved this to "Development Backlog".  I spoke with @curfman briefly and will submit a PR while considering a subtile, sections headings, and a hero image.  Also, final technical formatting issues may just take place on 'master' so it can be previewed.

**Comment by bartlettroscoe** [comment]
FYI: Just posted PR #377 with a draft of this blog article.  Do your worst :-)

**Comment by rinkug** [comment]
> I like the transparency of your blog. You share how you have struggled with decisions, gained insights from a thought leader, and made changes accordingly in your thinking. I believe there are other readers who will have been in your position, and will appreciate that you are courageous to share your struggles, and that your thinking changed after accessing a resource, and thinking further.
> 
> When I read your blog, I was interested and had many more questions. I think your blog would be strengthened with examples (if possible) and definitions of terms. For example, what is the validation-centric approach? What in the book was the tipping point to change your thinking? How did this perspective apply to your code? What changes did you make? Now that you know this, how has this changed the way you think and conduct testing?
> 
> As you flesh out the blog, think about telling the reader a story about your journey with details so they can “replicate it,” if needed. I think you are almost there with a few more details.

I liked some of Elaines comments here.

**Comment by bartlettroscoe** [comment]
CC: @curfman 

As of the updated generated display file in commit 957a639, this should be ready to publish.
