### ISSUE TITLE
GitHub communication best practices

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/betterscientificsoftware.github.io#375]
Author: Edward R.
EB member: Ross B.

[Here is a possible article](https://ben.balter.com/2014/11/06/rules-of-communicating-at-github/) on communication best bractices on github

I brief read suggested a lot of interesting and useful tidbits.

For me, it helps me *put the right thinking cap on* when starting an action on GitHub.

**Comment by bartlettroscoe** [comment]
@markcmiller86, I read the [whole thing](https://ben.balter.com/2014/11/06/rules-of-communicating-at-github/) and I am in violent agreement.  Some great bits:

> Email is a terrible, terrible collaboration medium, and an even worse mechanism for storing organizational knowledge.

> The great thing about issues and pull requests, in contrast to say, email, is that they can be bifurcated when topics diverge.

I have been arguing some of this stuff  for years but can't see to get traction.  People just always revert back to using email when they should be communicating through comments in Issues.  Very frustrating.

And, I have argued for BSSw to:

> Unless it’s a minor typo, so irrefutable that no one would possibly question it or need to be notified of the change, the only way to change community content is with a pull request. It doesn’t matter if it’s code, configuration, or internal policy.

But I also want to note that several of the items relate to weaknesses in it GitHub Issues compared to say JIRA.  For example:

* 5. Be mindful of noise
* 6. Use checklists to make blockers explicit

are workarounds for the weaknesses of GitHub Issues.  In JIRA, you can have minimal (or no) "Watchers" and then explicitly mention people you want to get emails about your updated comment.

I think it would be great to have a curated content article for this but have a disclaimer or two like this to note the weaknesses of using GitHub issues as a communication medium.

**Comment by rinkug** [comment]
> @markcmiller86, I read the [whole thing](https://ben.balter.com/2014/11/06/rules-of-communicating-at-github/) and I am in violent agreement. Some great bits:
> 
> > Email is a terrible, terrible collaboration medium, and an even worse mechanism for storing organizational knowledge.
> 
> > The great thing about issues and pull requests, in contrast to say, email, is that they can be bifurcated when topics diverge.

To play devil's advocate.. Folks who have not used git, github issues and pull requests (think non-technical program/project managers) tend to find it intimidating! It does have a learning curve.
 
> I have been arguing some of this stuff for years but can't see to get traction. People just always revert back to using email when they should be communicating through comments in Issues. Very frustrating.
> 

Some reasons I have been given is that emails (1)  feel more personal, (2) limited distribution, (3) available offline on local machine, (4) not archived on the web....I see some value in these reasonings  for perhaps some topics but I agree that for collaboration, emails do not work! For ex: I simply cannot figure out the github issue discussions via the emails I receive.

**Comment by bartlettroscoe** [comment]
@rinkug said:

> For ex: I simply cannot figure out the github issue discussions via the emails I receive.

What do you mean?

**Comment by rinkug** [comment]
> @rinkug said:
> 
> > For ex: I simply cannot figure out the github issue discussions via the emails I receive.
> 
> What do you mean?

I mean that its much easier to use the github web interface to read  and write comments coherently rather than trying to follow the issue conversations via the email notifications that one receives. This issue can perhaps be resolved by better formatting the github notification emails or putting more content in them - but in the larger scheme of things independent of github, emails are not the best method for facilitating discussion.

**Comment by bartlettroscoe** [comment]
> I mean that its much easier to use the github web interface to read and write comments coherently rather than trying to follow the issue conversations via the email notifications that one receives. T

In my opinion the best way to provide context is to do what I just did here.  You quote some targeted statement or question from a prior GitHub comment when you respond to it.  This should give enough to understand the context for that GitHub email.  To see the fuller context, just go to the GitHub issue itself.  This is **much** better than email threads.

**Comment by rinkug** [comment]
> > I mean that its much easier to use the github web interface to read and write comments coherently rather than trying to follow the issue conversations via the email notifications that one receives. T
> 
> In my opinion the best way to provide context is to do what I just did here. You quote some targeted statement or question from a prior GitHub comment when you respond to it. This should give enough to understand the context for that GitHub email. To see the fuller context, just go to the GitHub issue itself. This is **much** better than email threads.

Agree!

**Comment by markcmiller86** [comment]
@rusu24edward ... I would like to ask if you might be interested in reading the referenced article here and writing a short curated content article (a paragraph or two to introduce topic and/or summarize key points) for the bssw.io site? Let me know.

**Comment by rinkug** [comment]
Ping @rusu24edward

**Comment by rinkug** [comment]
Currently setting this to "Early October Issue". Might move it to later once new milestone tags are created and based on authors preference.

**Comment by rusu24edward** [comment]
Sorry for my delay on this. Will have this done before October.

**Comment by rusu24edward** [comment]
Just submitted through the contribution portal.

**Comment by bartlettroscoe** [comment]
@rusu24edward said:

> Just submitted through the contribution portal.

Where is that, specifically?

**Comment by markcmiller86** [comment]
@bartlettroscoe, it looks like @rusu24edward used the [form](https://bssw.io/contributes/new) on bssw.io site. Those entries get routed on a [google sheet](https://docs.google.com/spreadsheets/d/1u6CLr6LbVbbWnpUVij1_z_ugWwAy-5RI7d6QwyFxK00/edit#gid=1070285854) in the [ideas-ecp drive sub-folder](https://drive.google.com/drive/folders/16aqEAFY5ZxMV8if7__cwlE6866lFa7bd).

I went ahead and grabed the text and have put it below...

Ben Balter’s article “15 rules for communicating at GitHub” presents exactly so: 15 communication rules that GitHub employees follow to improve their overall workflow, rules that establish a communication strategy from which modern software development can greatly benefit. From these rules, here are the key underlying points that stand out to me:
    Be flexible with tickets. Many of us think of tickets as fully completed thoughts that require time and money to resolve. However, a ticket can be a question, a suggestion, an early idea that flowers into a great new feature, etc. A ticket is just the start of a conversation, and software teams can improve by cultivating an environment that promotes communication.
    Asynchronous communication means that everyone can get involved in the conversation. Instead of notifying a single @employee, you can notify the entire @team on a distributed and easy-to-track platform (such as GitHub issues). This opens up the conversation to whoever on your team is willing to get involved. Which leads to the next point:
    Only communicate if you can give time to the issue at hand. That is, put your money where your mouth is. If you have thoughts on an issue, you better have time to back up those thoughts before you share them. Otherwise, your comments can sidetrack or stall the conversation. As Balter says, “Avoid drive-by opinions.” 
    Finally, I feel it necessary to point out that having rules only matters if the team is dedicated to following them. I can think of many ways to break every one of Balter’s 15 rules. For example, you can enforce PR reviews by locking the merge button without approval, but this only matters if your reviewers are dedicated to actually reviewing the PR instead of blindly approving (say, because of a lack of time). For communication rules to effect positive change, the team must understand the context of the rule—why it is—and must agree to practice it. If so, then these communication strategies can provide a great boost in the pursuit of Better Scientific Software.

Eddie Rusu
Computational Scientitst
Lawrence Livermore National Laboratory

**Comment by rinkug** [comment]
See PR #424
