### ISSUE TITLE
Cannot figure out how to reply to a comment/question

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/betterscientificsoftware.github.io#381]
@bartlettroscoe ... when I go [here](https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/commit/1a4162465661899611f6c3463fbf7c110a0bca43#diff-95e0934d35c44038c0b9d532bc1d07f4), there is a comment/question at the top of the page, such as depicted in the screen-capture below and for which I have no idea where to go to respond to it. How did this comment get there? Do you know where I can go to reply?

![Untitled](https://user-images.githubusercontent.com/5720676/59394137-7fe3e100-8d33-11e9-9c97-991feb45b8ab.png)

**Comment by bartlettroscoe** [comment]
@markcmiller86, which comment?  The one here:

* https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/commit/1a4162465661899611f6c3463fbf7c110a0bca43#diff-95e0934d35c44038c0b9d532bc1d07f4R263

?

**Comment by markcmiller86** [comment]
Nope...but on that same page at the top, as shown in the attached picture, that reads...

```
Update ApolloGuidanceComputerPart2.md
Do you need to define or spell out LM and CM, DSKY, and LVDC?
The rest looks good.
```

**Comment by bartlettroscoe** [comment]
That is the git commit log message.

**Comment by markcmiller86** [comment]
Ah, ok, I guess I hadn't taken note of that before.
