### ISSUE TITLE
Possible Curated Content - Dummy test

### ISSUE THREAD

**Issue by rusu24edward** [betterscientificsoftware/betterscientificsoftware.github.io#386]
* My reference to the resource
* Why I think this is facinating:
    * Point number 1: it rocks
    * Point number 2: it's better science
    * Point number 3: it's open source
* Not sure actually. Just putting this here in case you find it interesting ;)

**Comment by markcmiller86** [comment]
thanks @rusu24edward ... In theory, I should be able to *assign* you to the issue based on [this](https://github.blog/2019-06-25-assign-issues-to-issue-commenters/). But, I am not seeing your name appear in the pull down list. Maybe there is a setting I need to find.

**Comment by markcmiller86** [comment]
Ok, so I just now succeeded in assigning you.

Although I didn't see you in the list, typing in the first few chars of your github handle worked.

Thanks for submitting this test issue.

@bartlettroscoe and @bernhold this confirms we can assign an author who is a submitter.

Next, I wanna confirm we can assign a commenter as well.

**Comment by aowen87** [comment]
Comment from Alister.

**Comment by markcmiller86** [comment]
Ok, cool. 

GitHub has this new feature just out last week that allows assigning a submitter or commenter.

Thanks for the help in testing.
