### ISSUE TITLE
Problem with web site?

### ISSUE THREAD

**Issue by jarrah42** [betterscientificsoftware/betterscientificsoftware.github.io#388]
Is there a problem with the bssw.io web site? I don't see any blog articles or events when I view the site. I've tried both Safari and Chrome with the same result (also tried emptying caches, etc.).

**Comment by markcmiller86** [comment]
Yeah, there is a problem. They are aware of it. Won't be fixed 'til tomorrow

**Comment by curfman** [comment]
Site is back up.  Thank you @clararaubertas .
