### ISSUE TITLE
Possible Blog Article

### ISSUE THREAD

**Issue by luszczek** [betterscientificsoftware/betterscientificsoftware.github.io#393]
Hi,

I submitted a pull request for a new blog post about xSDK:

https://github.com/betterscientificsoftware/images/pull/4

Thank you,

Piotr

**Comment by curfman** [comment]
Piotr: Thanks for communicating so clearly about xSDK community policies and considerations. This article will be a valuable resource for the community.

All:  We previously communicated with Piotr and Ulrike about this blog article, and they have kindly agreed to help us flesh out the BSSw workflow as we progress through the next steps with this article.

**Comment by bernhold** [comment]
Note that Piotr has already supplied a PR (#390) for this article.

**Comment by bernhold** [comment]
I am closing this issue in favor of PR #390.   I think we can work with just the PR from here on.

The image PR is already noted in #390.
