### ISSUE TITLE
CC Article on Open Source Sustainability

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/betterscientificsoftware.github.io#396]
Author:Paul 
EB member: Mark M.

Found [this article](https://www.vice.com/en_us/article/43zak3/the-internet-was-built-on-the-free-labor-of-open-source-developers-is-that-sustainable) on open source sustainability. I read in its entirety. It is a bit of a long read (or I am a slow reader)

* Provides a nice history of how open source evolved from 1980s
* Uses specific (success and failure) examples of projects and people to tell the story of how open source projects last (or not).
* Explains that resources like GitHib have really helped improve sustainability of open source.
* Is slanted towards commercial open source and not specificaly to HPC/CSE open source which is a bit of a different *market* IMHO anyways.
* Is a recent article, from Feb 2019

**Comment by prwolfe** [comment]
I agree that the length is a bit of an obstacle, but I see a lot of HPC/SCE issues here. All of our current clusters run Linux for the OS and TensorFlow is becoming the backbone of a lot of CSE work. 

I was struck by the discussion of how to allow resources (time, money and autonomy) to be properly allocated and distributed in FOSS.  I would like to see this idea developed.

**Comment by rinkug** [comment]
Paul to consider writing this!

**Comment by prwolfe** [comment]
Mark,

At todays meeting we discussed this one and decided I should not be both assignee and author.  You willing to be the assignee?  

Paul

**Comment by markcmiller86** [comment]
This was resolved by [this work](https://github.com/prwolfe/betterscientificsoftware.github.io/blob/2d63173b8f45d348a65cc4b7a010c2a85ef4ffaa/CuratedContent/EconomyOfOpenSourceSW.md)

**Comment by rinkug** [comment]
Published : https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/EconomyOfOpenSourceSW.md
