### ISSUE TITLE
Math rendering?

### ISSUE THREAD

**Issue by gonsie** [betterscientificsoftware/betterscientificsoftware.github.io#405]
Does the bssw website support mathjax (or something else) for in-line math editing? This issue was raised by @markcmiller86 in #397. That PR was able to get around the issue by using built-in HTML symbols... but the equations are not rendered as beautifully as they could be.

@markcmiller86 has an [example of Latex/MathJax](https://xsdk-project.github.io/MathPackagesTraining/lessons/hand_coded_heat/), but it assumes some backend support.

**Comment by markcmiller86** [comment]
@gonsie if we can't find support on the back-end, all is not lost. A few years ago, I was doing business [this way](https://xsdk-project.github.io/HandsOnLessons/lessons/hand_coded_heat/lesson.html) and it worked ok. Just uuencoding the equation text was a pain and not easily edited later. But, it worked ok.

**Comment by markcmiller86** [comment]
@bsswimagery or @curfman can you comment regarding support for math equations in blog articles.

**Comment by rinkug** [comment]
This is now closed.
