### ISSUE TITLE
Blog article highlight differences in expections in hires from commercial and academia

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/betterscientificsoftware.github.io#408]
Had a conversation with @csnavely at SMC about this topic. Might make for a good blog article. Cory, if you have a moment to jot down some key points here in this issue, that might get the ball rolling.

**Comment by bernhold** [comment]
Maybe I need to hear more of the content of this discussion from @markcmiller86 .  Are we really talking about *hiring* here?  Is that in scope for BSSw?  What is the connection to software productivity and sustainability types of things?

**Comment by markcmiller86** [comment]
Hmmm...its been a few weeks now and I can't recall all the details but the comments had to do with software productivity and the *thinking cap* commercial vs. academic hires have. Commercial people tend to come with an *issue ticket* mentality w.r.t. software productivity...just give me the issues I am supposed to be responsible for. Academics come with a different mentality (which I can't recall now). This impacts the onboarding process as well as general expectations new hires have w.r.t. to the software development responsibilities.

**Comment by rinkug** [comment]
Need more information on the scope of the actual topic, especially if it is a blog. Please put link to cc article if we plan to go with curated content here. I gave it a confused sign to indicate that I have reviewed  this

**Comment by rinkug** [comment]
Closed due to insufficient interest
