### ISSUE TITLE
Add curated: Why do programmers wear headphones?

### ISSUE THREAD

**Issue by maherou** [betterscientificsoftware/betterscientificsoftware.github.io#41]
Why do programmers wear headphones? For the same reason that you can’t juggle.
https://hackernoon.com/why-do-programmers-where-headphones-5ca3a2f81266#.ykhfxv2b4

**Comment by pagrubel** [comment]
I agree with Rinku I think the alternate Deep Work is more worthwhile

@bartlettroscoe : "Steve McConnell covers the need for focus and the impact of distractions in his book "Code Complete 2nd Edition". Do you already have an article on this book. I remember you mentioned it somewhere.

**Comment by rinkug** [comment]
Should this be closed since the we have the "deep work" article in works now

**Comment by JeanShuler** [comment]
I don't think this is relevant in my work environment where everyone collaborates - and no one uses headphones

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe : "Steve McConnell covers the need for focus and the impact of distractions in his book "Code Complete 2nd Edition". Do you already have an article on this book. I remember you mentioned it somewhere.

@pagrubel, Osni provided one:

* https://bssw.io/items/code-complete-a-practical-handbook-of-software-construction

But any short overview can't possibly touch all of the topics covered in the book.  

BTW: That book is super important and is my number-1 recommended book on software development:

* https://bartlettroscoe.github.io/reading-list/#code_complete_2nd_edition_2004

**Comment by rinkug** [comment]
This is closed and issue #417 for Deep work has been created
