### ISSUE TITLE
Deep Work

### ISSUE THREAD

**Issue by jarrah42** [betterscientificsoftware/betterscientificsoftware.github.io#417]
Author: @jarrah42 

Deep work is the ability to focus without distraction on a cognitively demanding task. It’s a skill that allows you to quickly master complicated information and produce better results in less time. Deep work will make you better at what you do and provide the sense of true fulfillment that comes from craftsmanship. In short, deep work is like a super power in our increasingly competitive twenty-first century economy. And yet, most people have lost the ability to go deep—spending their days instead in a frantic blur of e-mail and social media, not even realizing there’s a better way.

http://www.calnewport.com/books/deep-work/

Also a great podcast:

https://www.npr.org/2019/08/26/754336716/you-2-0-deep-work

**Comment by rinkug** [comment]
@jarrah42 : Greg, Can I close this issue and move the discussion to the PR #421, so that we are  consistent with the workflow for curated content?

**Comment by jarrah42** [comment]
+1

**Comment by jarrah42** [comment]
This needs someone from the EB to shepherd.

**Comment by rinkug** [comment]
> This needs someone from the EB to shepherd.

I will shepherd this. Moving this to in-progress.

**Comment by rinkug** [comment]
Please refer to PR #421
