### ISSUE TITLE
personal kanban

### ISSUE THREAD

**Issue by rinkug** [betterscientificsoftware/betterscientificsoftware.github.io#418]
Author: Pat

A possible CC on  https://hackernoon.com/personal-kanban-part-1-why-todo-lists-don-t-work-3b5c6dc78708

Relates to closed issue #130

**Comment by markcmiller86** [comment]
The article doesn't say anything about handling *interrupts* and *context* switching which in my world and those of other HPC software developers split across multiple tasks and customer support tends to be a significant portion of my time.

**Comment by pagrubel** [comment]
Previous to having this in another issue, I  didn't have a personal kanban. I have recently started one, so I think this is valuable. I'd add that you can easily create one using a git repo. That's what I decided to do for work in a local private gitlab repo. They push using Trello in Part 2.

**Comment by rinkug** [comment]
I use personal kanban and I think this is valuable

**Comment by bartlettroscoe** [comment]
I do a poor-man's version of personal Kanban for trying to limit WIP and keeping track of the next most important things to do.  I did not read into the whole article but hopefully they don't screw this up. So I voted yes.

**Comment by bernhold** [comment]
@pagrubel any progress on this?  Thanks

**Comment by pagrubel** [comment]
Adding a couple of links for possible reference here:
his part 2 using Trello mentions other solutions as well
https://hackernoon.com/personal-kanban-part-2-personal-kanban-with-trello-a6bd6cdb0588
using gitlab issues (can be done with github also)
http://gbraad.nl/blog/task-management-and-personal-kanban-how-i-use-gitlab-issues.html

**Comment by pagrubel** [comment]
This is on my personal kanban board to write tomorrow!

**Comment by pagrubel** [comment]
I have this written just needs to go through my local approval, hopefully in a day or two

**Comment by rinkug** [comment]
PR #507 created for this
