### ISSUE TITLE
Lack of Evidence In Software Engineering

### ISSUE THREAD

**Issue by jarrah42** [betterscientificsoftware/betterscientificsoftware.github.io#420]
Author: Greg

IEEE Computer has a great article titled "Methodological Irregularities in Programming-Language Research" that everyone should read. In particular, I quote "... [a review] of the evidence standards of research presented at the International Conference on Functional Programming from its founding in 1996 to 2014 and found that not one study followed methodological guidelines... Nevertheless, this research community has vehemently and successfully argued for the inclusion of functional features in popular programming languages such as Java, C++, and Snap!"

https://ieeexplore.ieee.org/document/7999115

**Comment by markcmiller86** [comment]
FWIW...I find this far to the abstract end of the nuts-n-bolts software producitivity spectrum. To be clear, it *is* interesting. But, I want a mix of nuts-n-bolts and abstract content of about 70/30.

**Comment by markcmiller86** [comment]
Also, do we *need* to provide rationale for our votes? I mean, I could maybe understand if my vote was somehow special. But, with a sufficient number of votes, the *average* should be sufficient measure of a proposed idea's merit for site without having to engage in discussion about it.

**Comment by bernhold** [comment]
My thinking is that, in the long run, Topic Review should be a quick thing that shouldn't require a lot of discussion or explanation.

But right now, we're trying to figure out what we want BSSw to be when it grows up, and at this stage, I think the discussions are probably necessary to developing a consensus on the kind of content we want to have.

So right now, I feel like it is fair to ask for rationales and otherwise discuss.

**Comment by jarrah42** [comment]
> Also, do we _need_ to provide rationale for our votes? I mean, I could maybe understand if my vote was somehow special. But, with a sufficient number of votes, the _average_ should be sufficient measure of a proposed idea's merit for site without having to engage in discussion about it.

The average would work if everyone voted, but I don't think we're at that point yet.

**Comment by jarrah42** [comment]
> My thinking is that, in the long run, Topic Review should be a quick thing that shouldn't require a lot of discussion or explanation.

I was in agreement until it was my suggestion that got down voted. :wink:

**Comment by rinkug** [comment]
@prwolfe has interest in reading this and following up

**Comment by rinkug** [comment]
PR #451 has been opened for this issue
