### ISSUE TITLE
National RSE Organizations

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/betterscientificsoftware.github.io#432]
Author: Rinku Gupta

I think it would be good to have a resource that pointed to national RSE organization web sites.

http://rse.ac.uk/
http://de-rse.org/
http://nl-rse.org/
http://nordic-rse.org/
http://us-rse.org/

Note: this kind of duplicates https://researchsoftware.org/, but I think it is useful content for BSSw to have too.

**Comment by rinkug** [comment]
PR #452 created for this issue.
