### ISSUE TITLE
Don't use "Curated Content" or "CC" in Issue titles

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/betterscientificsoftware.github.io#434]
Have a look at this snapshot of issues...

![Untitled](https://user-images.githubusercontent.com/5720676/67221142-cdf2aa80-f3df-11e9-933b-f69371097fda.png)

The words "CC" and/or "Curated Content" appear in titles but they don't need to because the issues have the "curated content ideas" already attached. Its just duplicate noise that reduces readability.

If there is no objection, I will plan to do the following before thursday's meeting

- remove "Possible Curated Content" from issue template
- add verbiage to template to not include "curated content" in the title
- Revise all existing issues and revise titles

**Comment by rinkug** [comment]
Thats fine with me.

**Comment by markcmiller86** [comment]
Ok, I took care of (most of) this. Only did it for still open issues.

having shorter headlines means email subjects will be a little easier to recognize too
