### ISSUE TITLE
Best Practices for Your Developer Onboarding Process

### ISSUE THREAD

**Issue by rinkug** [betterscientificsoftware/betterscientificsoftware.github.io#449]
This is an interesting onboarding article that I came across i.e if you are ignore (1) the swear words in the first para, (2) "7" (best practices) which many of us perhaps dont like in titles.

https://www.codementor.io/blog/developer-onboarding-process-32y3zqg1vc

**Comment by markcmiller86** [comment]
I voted this down because I felt it was a long read to find the tidbits of good practices there

**Comment by prwolfe** [comment]
It's a bit long, but makes th points well in the end.  I'm torn..

**Comment by pagrubel** [comment]
I have to agree with Mark and not sure the title is the best fit
