### ISSUE TITLE
Better Scientific Software Communities

### ISSUE THREAD

**Issue by hnamLANL** [betterscientificsoftware/betterscientificsoftware.github.io#467]
BSSw Fellowship 2019 - Rene Gassmoeller
Create curated content page for Better Scientific Software Communities found at https://gassmoeller.github.io/BSSC/

Then modify link at the bottom of his profile https://bssw.io/fellows/rene-gassmoeller
to link to the curated content versus the direct link to github.

**Comment by markcmiller86** [comment]
I like this idea. It struck me that many of the first several bullets of Rene's page are similar in spirit to those involved with on-boarding people to a new project.

**Comment by rinkug** [comment]
@markcmiller86 : Is this issue related to PR #493  ?

**Comment by markcmiller86** [comment]
> Is this issue related to PR #493 ?

Not certain but I don't think so. Based on comments in #493, that PR is related to issue #500

**Comment by rinkug** [comment]
> > Is this issue related to PR #493 ?
> 
> Not certain but I don't think so. Based on comments in #493, that PR is related to issue #500

Actually,  Issue #500 was created by me today for PR #493 to be consistent with our "issue leads to PR" editorial workflow...Did I end up duplicating the issue?

**Comment by rinkug** [comment]
The idea is to have a single curated content pointing to outcome of 2019 fellowships.
For each fellow, point to curated content/blog for that fellow on bssw.io

**Comment by rinkug** [comment]
We pointed to Rene's blog from his profile on BSSw.io. This is now closed.
