### ISSUE TITLE
Mine this spreadsheet for remote training wisdom/practices

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/betterscientificsoftware.github.io#480]
I happened to be emailed this spreadsheet link from SWC community and it includes a ton of university-specific links on how those organizations manage on-line teaching. But, there are a number of links to general guidelines, etc. for planning and executing on-line teaching. I thought it could make for a useful resource to go mine and extract *gems* from to include in content here.

https://docs.google.com/spreadsheets/d/1VT9oiNYPyiEsGHBoDKlwLlWAsWP58sGV7A3oIuEUG3k/htmlview?sle=true#

**Comment by rinkug** [comment]
This spreadsheet looks very good! Do you think a CC or a blog is better suited? If we are mining this, a CC may be too short for it? or not?

**Comment by markcmiller86** [comment]
Well, we can do a CC now to point to it and follow up later after expending some effort to go mine the material there.

**Comment by pagrubel** [comment]
So you want a CC or do you want to mine this for content that would be useful. It's rather overwhelming as is

**Comment by bernhold** [comment]
Can we remove the blog label from this?
