### ISSUE TITLE
Would an article on keeping work area clean during COVID-19 outbreak be a good idea

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/betterscientificsoftware.github.io#484]
Author: Mark Miller
EB member: Lois

It is certainly relevant. I don't know how much to include but keeping keygoard, cell phone, mouse, telephone handset, headset clean, eye glassies, etc. what the best cleaners are. How often? What the current guidance is on time CV-19 can live on surfaces, etc

**Comment by rinkug** [comment]
Need  to move to topic review since team members agreed to this verbally on Mar 12 call.

**Comment by bernhold** [comment]
@markcmiller86 did this turn into PR #492 ?  I think we can close this as done.

**Comment by rinkug** [comment]
Pe #492 is for a curated content of this article
