### ISSUE TITLE
Working Remotely in an Agile World

### ISSUE THREAD

**Issue by bartlettroscoe** [betterscientificsoftware/betterscientificsoftware.github.io#489]
Author: Ross (Written by Rinku)

This is a 48 minute video on "Working Remotely in an Agile World":

https://www.infoq.com/presentations/practices-working-remote/?utm_source=email&utm_medium=culture-methods&utm_campaign=newsletter&utm_content=11262019

This was highlighted in one of the InfoQ summary sent out a few months ago.

**Comment by bartlettroscoe** [comment]
I am watching this now and will post my notes here.

**Comment by bartlettroscoe** [comment]
CC: @rinkug, @markcmiller86, @curfman, @maherou, @elaineraybourn 

My notes from this 48 min presentation are below.

In summary, I think there is some good advice in this presentation and the speaker addresses some issues that I have not seen addressed before like "water cooler" moments and she covers many of the other challenges in communication in a distributed team.  So I think I would recommend publishing a curated content article for this.

One of the big drawbacks was that she asks lots of questions from the audience and requests feedback during the talk, but you can’t really hear what they are saying because they are not given a microphone.

----

**My notes on the presentation:**

* Remote teams:
  * Enhances access to talent for people that will not move to your location.
  * Teams work well by adopting effective communication techniques.
    * Collocated people who are talking need to pause frequently and see if remote people have something to add to the conversation.
    * Remote people should be able to interrupt to get a point across and collocated people should not be offended by this because the lag makes it looks rude.
  * Leadership is not reliant on location.
    * Don’t micro-manage remote people
    * Trust: By default, assume that remote people are working and want to contribute
    * Be flexible to meet at odd times to accommodate different timezones. 
* Invest in Tech:
  * Get good audio/visual-conferencing systems (a different screen for every office and team-room).
  * Do regular one-on-one meetings with remote people.
* Have team days:
  * Get everyone together in the same location on a regular basis
  * Do these whenever there is a change in the team (new team members)
* Error on the side of over-communicating:
  * Reconfirm that was said
  * Rule of 7 (repeat it 7 times)
* Create steams of work (channels):
  * Avoid getting spammed by too many messages (i.e. Slack)
* Have each developer enable an always-on camera with an active speaker so that you create a virtual team room.  (Be mindful you are always on camera and be careful to turn it off when you are away from work.)
* Spend more time preparing for interactions with other team members than you would if you are co-located.
*  Find ways to create “water cooler” moments.
  * There are phone apps to tell you when someone is away from their desk and at the “water cooler” so you can try to reach them then when they are not engrossed in something.
* Don’t hesitate to pick up the phone to call a team member or answer a phone call from a team member (if it will be something short and not a long drawn-out meeting).
* Switch off when not needed (or need personal time to focus on something).
  * For example, in an office where a developer has on headphones, you don’t disturb them.
* Speak up at meetings and advertise your work.
* Use co-working spaces so you don’t feel lonely
* Reach out to people.
* Create a special home work-zone and don’t mix work space and home space.
* Take time for yourself and take care of yourself
* Working remotely is a perk for both the employer and the employee, enjoy it.
* Establish clear work times and don’t assume you will not work all the time.

**Comment by markcmiller86** [comment]
FWIW...I am not sure sending bssw visitors to a ~50min YouTube video via CC article is best course of action. I think we might need to find some resources to *distill* the shared wisdom of this resource and others into a HowTo or Blog or something.

**Comment by rinkug** [comment]
Ross notes on this article are pretty good! Would it be wise to write a cc with the notes in the text and a pointer to the video? or would that be considered transcribing the video (since the notes are kind of detailed (which is good!))

**Comment by markcmiller86** [comment]
> Ross notes on this article are pretty good! Would it be wise to write a cc with the notes in the text and a pointer to the video? or would that be considered transcribing the video (since the notes are kind of detailed)

I agree. Maybe take top 3-5 relevant bullets from Ross' notes and use them to create CC article with pointer to video.

**Comment by rinkug** [comment]
@bartlettroscoe Do you have time to write a good para or two on this video or shall I write one?

**Comment by elaineraybourn** [comment]
@bartlettroscoe this is great list. Would we want to consider adding these tips to a team blog of best practices?

**Comment by bartlettroscoe** [comment]
> Do you have time to write a good para or two on this video or shall I write one?

@rinkug, if someone has already watched the video, they can write this up.  Otherwise, I can take a stab at this on Friday.

> Maybe take top 3-5 relevant bullets from Ross' notes and use them to create CC article with pointer to video.

@markcmiller86, what would be wrong with trimming up the bullets and providing them as part of the CC article?  I think you can read that list of bullets and think about them in 5 minutes.

**Comment by markcmiller86** [comment]
> @markcmiller86, what would be wrong with trimming up the bullets and providing them as part of the CC article? I think you can read that list of bullets and think about them in 5 minutes.

Nothing wrong. Just easier, simpler, faster. If you wanna do the whole shootin' match, thats great! 👍

**Comment by rinkug** [comment]
@bartlettroscoe @markcmiller86 I am also in favor of the whole list. 

Ross, I can take a stab at it tomm if I get a chance. Else you do it on friday (I know you are very busy too...)

**Comment by bartlettroscoe** [comment]
> Ross, I can take a stab at it tomm if I get a chance. Else you do it on friday (I know you are very busy too...)

@rinkug, okay, let me know if you can't get to this.

**Comment by pagrubel** [comment]
@paul will you have time to do this as discussed yesterday, if not I can at the end of today

**Comment by pagrubel** [comment]
@prwolfe will you have time to do this as discussed yesterday, if not I can at the end of today

**Comment by prwolfe** [comment]
?It looks like I am not going to get to this. My manager asked for some stuff by end-of-day that will keep me running. Sorry about that.


Paul


________________________________

**Comment by bartlettroscoe** [comment]
I will work on this after I get some near-due training done which might not be till Monday.

**Comment by rinkug** [comment]
I have time today and I will work on this now.

**Comment by rinkug** [comment]
Created PR #502
