### ISSUE TITLE
Start a CC roll for computing in relation to pandemic

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/betterscientificsoftware.github.io#496]
Some sources I've already found

- [Hospital Bed Projection Models](https://projects.propublica.org/graphics/covid-hospitals)
- [JH Coronavirus World Case Tracker](https://coronavirus.jhu.edu/map.html)
- [WAPO 2D Simulations of Various Social Distancing Strategies](https://www.washingtonpost.com/graphics/2020/world/corona-simulator/)
- [China uses AI for Contact Tracking](https://www.aljazeera.com/news/2020/03/china-ai-big-data-combat-coronavirus-outbreak-200301063901951.html)
- [AI to Help Fight COVID-19](https://www.forbes.com/sites/bernardmarr/2020/03/13/coronavirus-how-artificial-intelligence-data-science-and-technology-is-used-to-fight-the-pandemic/#763c80835f5f)
- [Complexities of Pandemic Modeling](https://www.the-scientist.com/news-opinion/modelers-struggle-to-predict-the-future-of-the-covid-19-pandemic-67261)
- [Summit used to Speed Identification of Possible Vaccines](https://www.independent.co.uk/life-style/gadgets-and-tech/news/coronavirus-vaccine-supercomputer-ibm-summit-ai-covid-19-a9413411.html)
- [TACC Simulations help Identify key Protien in SARS-CoV-2 Replication](https://www.hpcwire.com/2020/03/19/tacc-supercomputers-run-simulations-illuminating-covid-19-dna-replication/)
- [H1N1 Pandemic Modeling and Managing Recurrences](https://www.hpcwire.com/2020/02/26/supercomputer-helps-tackle-pandemic-flu-simulations/)
- [How you can add your own personal computer to the fight against COVID-19](https://www.weforum.org/agenda/2020/03/covid-19-distributed-computing-vaccine/)

**Comment by markcmiller86** [comment]
Without too much trouble, I've found and read 10 articles about use of computing in either educating the public about the pandemic or in modeling various aspects.

**Comment by rinkug** [comment]
I like the idea. Need to run it via @curfman since it mentions the pandemic by name.

**Comment by bernhold** [comment]
The pandemic that shall not be named?

**Comment by pagrubel** [comment]
Can we keep up with this?

**Comment by rinkug** [comment]
We decided that we will not be able to keep up with articles, being published, on the web.
