### ISSUE TITLE
Teleconference tool tips for HPC/CSE users and teams

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/betterscientificsoftware.github.io#498]
Lets create a curated content article that takes the form of a table with tools across the top and features down the left side kinda sorta like below (only here as an example, not to suggest only these topics. This table is constructed so that feature headings link to descriptive sections below table (I am not sure I've got the markdown correct for that here but if not will resolve shortly) and that yes/no/partial links to best resource for that product's explanation/training of that feature. The features listed are just a start informed from [today's meeting notes](https://docs.google.com/document/d/1MUoOBqamOJia1NoPsXron3xelzggdSDoimLVFQFIrKc/edit)

Feature | [Zoom](https://www.zoom.us) | [WebEx](https://www.webex.com) | [BlueJeans](https://www.bluejeans.com) | [MS Teams](https://teams.microsoft.com/start) | other 2
--- | --- | --- | --- | --- | ---
[Breakout Rooms](#breakout-rooms) | [👍](https://support.zoom.us/hc/en-us/articles/206476093-Getting-Started-with-Breakout-Rooms) | [:fist_left:](https://help.webex.com/en-us/8cckd2/Manage-Breakout-Sessions-in-Cisco-Webex-Training) | [:+1:](https://www.bluejeans.com/blog/introducing-bluejeans-breakout-sessions) | [:+1:](https://techcommunity.microsoft.com/t5/microsoft-teams-blog/introducing-microsoft-teams-rooms-updated/ba-p/323848)
[Voting](#voting-or-polling) | [Yes](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings) | [Yes](https://help.webex.com/en-us/n0pdj9x/Start-a-Poll-in-Cisco-Webex-Meetings) | [Partial](https://support.bluejeans.com/s/article/Event-Polling) | [Yes](https://support.office.com/en-us/article/create-a-poll-in-microsoft-teams-a3f9112c-01e1-4ee4-bd88-25e4e243b80b)
App Sharing |
multiple displays |
shared whiteboard |
shared annotations |
recording |
chat |
blockout background |
test meetings |
not-compatible-with |
raise hand |
requires client download |

### Breakout Rooms

This is a feature that makes it possible for a single meeting to be broken into sub-meetings among smaller groups of participants and, after a period of time, re-joined back into the single large meeting.

### Voting or Polling

This is a feature that allows the host to ask participants a question and have then anonymously vote their responses.

### Screen Sharing

This is a feature that allows the host/presenter to share everything on his/her screen with all the participants. All teleconference tools support this feature. However, a number of tools also support variations of this feature for different needs. These are described below.

### App Sharing

App (or Application) sharing is like [*Screen Sharing*](#screen-sharing) except that the window(s) of only a single application (e.g. PowerPoint or Word) is shared.  The host/presenter is not forced to share their whole screen but can select only the window(s) from a specific application to share. This can be useful in cases where the host/presenter tends to have a lot of windows open and they want to keep the participants from accidentally seeing the contents of those other windows. When you have a choice, using application-specific sharing is a **best practice**.

### Shared Annotations

This is similar to but not quite the same thing as [*Screen Sharing*](#screen-sharing). Shared annotations allows the presenter/host to draw annotations on top of whatever content is being displayed in the main window so that all other participants can see it.

### Shared Whiteboard

This is similar to but not quite the same thing as *Shared Annotations*. A shared whiteboard is a separate drawing area, like a whiteboard in an office, where all participants can doodle content and paste images they captured locally.

**Comment by markcmiller86** [comment]
Ok, so in the markdown, above, I am using the correct [GitHub Flavored Markdown (GFMD) syntax](https://github.github.com/gfm/) for the links from the feature headings in the table to the level 3 headings in the text below. If you just cut-n-paste the raw markdown text into our wiki pages (as markdown), it works correctly. I think that GiHub issues don't fully support all of GFMD.

So, what do people think of this structure? The table is nice and concise highlighting the key features many of us need for using the tools for our needs.

We could break the table into a few different sections; one about the tools and features, another about the use cases that @jd-moulton and @maherou suggested.

**Comment by markcmiller86** [comment]
I edited the above comment to use a row of github emojis instead of the text `Yes` or `No`. A challenge is that there is nothing indicating that those emojis are actually links to something else until you hover over them. So, probably not the best idea.

**Comment by bernhold** [comment]
If this is intended for BSSw.io, I would not assume the emojis are available.  I don't think BSSw supports GFMD exactly.  And the style sheets used on BSSw are sometimes very different in how things are styled.  I suggest some experiments on the preview site before you get creative.

**Comment by markcmiller86** [comment]
> I suggest some experiments on the preview site before you get creative.

Thanks for the reminder 😢

**Comment by markcmiller86** [comment]
Moved to #499
