### ISSUE TITLE
Impact of COVID-19 on DOE Labs

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/betterscientificsoftware.github.io#512]
Just heard a great presentation from management of Computations at LLNL. Some of the interesting things in it had to do with increase in VNC usage (from 400 daily to 4000 daily users), increase in issue ticket filing, increase in laptop deployment rates, etc. doing remote ergo evalues, GIS-based tracking of COVID-19 infection rates on track-by-track basis in the communities around LLNL, etc. Another interesting thing is increase in computing power (about 15 petaflops) from *donations* of computing hardware from vendors and some of the computing efforts going into COVID-19 reasearch.

Am wondering if any other labs might have similar stories to tell, data to share in the way of impact of alterations in operations for COVID-19?

These could make an interesting blog article...especially the part about added computing resources due to vendor *donations*. I will be getting a copy of the slides from LLNL briefing this week.

**Comment by bernhold** [comment]
I know ORNL has its PR machine fully behind touting our impact on COVID research.  I'm sure all the other labs do too.  And my news feed is full of half a dozen stories per day of facilities and vendors donating computing resources to COVID work.  I'm not sure we can or should try to compete with this.  Additionally, I don't think we have first-hand knowledge, and I don't think they really fit in our scope.

What I think could be interesting is to look for some "behind the scenes" stories of how computational teams have dealt with software challenges when trying to address the urgency everyone feels in this crisis.  However we also have to recognize that the people on the ground in this may not have time to write anything for us while the crisis remains forefront.
