### ISSUE TITLE
Suggested update to https://bssw.io/items/resources-for-maximizing-remote-working

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/betterscientificsoftware.github.io#514]
Received via bssw-info:

> Contact: I have a suggestion for the site
Name: Sylvester Jalnaiz
Email: sylvester@f4s.com
Message: 
Hello there,
I recently stumbled on this post on your site: https://bssw.io/items/resources-for-maximizing-remote-working where you compiled a number of insightful resources for remote working.
One of my colleagues recently wrote this interesting and relevant piece which I want to share with you.
The article is entitled '23 remote team building activities (to boost morale and trust)' and it features an extensive compilation of creative team building ideas for remote teams. I believe this resource will be of great value to your readers especially in this time where companies are shifting their focus towards remote teams.
Hope you'll give it a read. Here's a link: https://www.fingerprintforsuccess.com/blog/team-building-activities
And lastly, I was just wondering if you could also include it to your list of resources? 
Please let me know.
~Sylvester

**Comment by elaineraybourn** [comment]
The suggestion is appreciated and noted. No further action will be taken at this time.

**Comment by bernhold** [comment]
Reopening so that we can use it to consider how to manage "update content" issues in a more general sense.

**Comment by rinkug** [comment]
This discussion is now moved to Issue #521
