### ISSUE TITLE
Items to add to telecom tools

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/betterscientificsoftware.github.io#531]
* bandwidth management in WebEx (each attendee can turn off receiving other's video)
* Zoom chat doesn't persistence...attendees don't see chats that occured prior to their arrival.

**Comment by markcmiller86** [comment]
You cannot share computer audio in WebEx. This means if you are sharing content with audio, no attendees will hear it. There some hacks to try to fix this but none are very good. Zoom supports shared audio.

**Comment by rinkug** [comment]
See PR #539
