### ISSUE TITLE
Possible Blog Article: Experiences porting code to the HIP ecosystem

### ISSUE THREAD

**Issue by hartwiganzt** [betterscientificsoftware/betterscientificsoftware.github.io#540]
Witnessing an explosion-like diversification in hardware architectures, hardware portability and the ability to adopt new processor designs has become a central property characterizing software sustainability. In this blog article, we report and discuss the experience of porting CUDA code to AMD's Heterogeneous-Computing Interface for Portability (HIP).

Maybe a little too early, I already formulated the complete blog article [here](https://github.com/hartwiganzt/betterscientificsoftware.github.io/blob/master/Articles/Blog/PortingToHIP.md).

Pull request #541

**Comment by bernhold** [comment]
Thanks Hartwig! The timing is excellent.  We'll work in getting it ready!

**Comment by bernhold** [comment]
Followups to PR #541
