### ISSUE TITLE
Create sample announcement

### ISSUE THREAD

**Issue by clararaubertas** [betterscientificsoftware/betterscientificsoftware.github.io#59]
Create a file in the format of a sample announcement, containing the metadata an announcement should have.

**Comment by sbxchicago** [comment]
An announcement will be the promotion of either a Blog Post or an Event page so is the request here for an Event page? Or should we close this issue?

**Comment by clararaubertas** [comment]
We have event posts already -- if we coiuld get a sample of either event or blog with whatever metadata will indicate that it's promoted, that would address this.

**Comment by curfman** [comment]
Done, see new metadata in 2 upcoming events:  Conference.ScientificSoftwareDays17.md, Workshop.SE4Science17.md ... Still need to consider global schedule of announcements (not just perspective of a particular event or blog post).

**Comment by sbxchicago** [comment]
Announcement success from what I can see. Only one announcement shows at a time so even though two were promoted to announcements, one displays on homepage
