### ISSUE TITLE
Add curated article on writing tips for documents

### ISSUE THREAD

**Issue by maherou** [betterscientificsoftware/betterscientificsoftware.github.io#63]
Add curated page for this useful link on how to write:

https://medium.com/@johnamwill/9-simple-but-powerful-ux-writing-tips-for-designers-83ec1ca96561

**Comment by pagrubel** [comment]
I really don't see where this would fit that well for bssw.

**Comment by rinkug** [comment]
I agree with Pats comment above

**Comment by rinkug** [comment]
Lack of interest
