### ISSUE TITLE
Homepage: Text edits in Hero Box

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#64]
- Remove “homepage” H1
- Remove "Content on the Better Scientific Software Site is organized in six broad categories"  and the 6 bullets that follow. (Clara will add "Resources for Developer Productivity and Software Sustainability" text to this page

**Comment by curfman** [comment]
Done.

**Comment by sbxchicago** [comment]
Looking at the display, Three issues:  
1 - The links you added show as bullets 
2 - They are followed by additional erroneous links
3 - We need non-linked language saying "Get Oriented:" to proceed these links

Can you make the fix? Or do we need to ask Clara to remove the incorrect links? Would you need her to display your links in a horizontal arrangement?
