### ISSUE TITLE
Homepage: Tech issues

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#67]
- Is the “See more” link intended to stand in for an announcement? If no, it should go, right?
- A line of text needs to be added to the homepage below the top block and above the categories. It should say: “Resources for Developer Productivity and Software Sustainability”. It might change in the future, but not on a regular basis. Could be static if easiest.

**Comment by clararaubertas** [comment]
Looks like there's a blank announcement in there for some reason, which is not correct. I'll investigate.

Will add headline as well.

**Comment by clararaubertas** [comment]
blank announcement fixed, headline added

**Comment by sbxchicago** [comment]
Headline looks good, but now, knowing this is an announcement, this should link to the blog post indicated. Link is broken.

**Comment by sbxchicago** [comment]
Also, is should have a post date and "Announcement" slug per page 3 of wireframes. Whole bar will be a single link.

**Comment by clararaubertas** [comment]
OK, should be fixed!
