### ISSUE TITLE
Top Nav: Dropdown menu

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#68]
- Find Resources dropdown is missing "All Resources" option
- Resources in Find Resources dropdown menu need to be in same order as wireframe

**Comment by clararaubertas** [comment]
How do you want to set the category order here? Since categories are automatically imported from the github site, they would need some kind of metadata to indicate their order if we want to go with something other than alphabetical.

**Comment by sbxchicago** [comment]
Should I ask Lois to indicate a specific order in metadata? Does it add work on your end? 2 hours? More?

**Comment by clararaubertas** [comment]
~2 hours sounds right for getting a specific order out of metadata -- let me know, thanks!

**Comment by clararaubertas** [comment]
Checking on whether this is something we're doing.

**Comment by sbxchicago** [comment]
Lois adding category metadata

**Comment by sbxchicago** [comment]
Lois has added metadata at this point.

**Comment by clararaubertas** [comment]
The homepage and dropdown should now reflect the order in metadata.
