### ISSUE TITLE
Add SW Sustainability is now an economic benefit

### ISSUE THREAD

**Issue by maherou** [betterscientificsoftware/betterscientificsoftware.github.io#7]
[
http://www.economist.com/news/science-and-technology/21695377-professors-unprofessional-programs-have-created-new-profession-more](http://www.economist.com/news/science-and-technology/21695377-professors-unprofessional-programs-have-created-new-profession-more)

**Comment by prwolfe** [comment]
Ties back to Software Carpentries founder and makes the point that funding and incentives cause a good bit of the issue.

**Comment by jarrah42** [comment]
This is behind a paywall. I don't think we should link to articles that are not accessible, or at the very least we should have a policy on it.

**Comment by markcmiller86** [comment]
Agree with @jarrah42. We should have a policy on this.
