### ISSUE TITLE
Blog: Landing page 

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#73]
- "See More" link shouldn’t be on this page, right?
- No filter will be included in Blog for launch
- Quotes only appear on homepage

**Comment by clararaubertas** [comment]
Are announcements supposed to appear only on homepage? If so, will remove from all other pages.

Will remove filter from blog.

Will remove quotes from other pages.

**Comment by sbxchicago** [comment]
Yes for launch announcements only appear only on homepage. Down the road they may appear on Community pages (a.k.a. Information For pages)

**Comment by clararaubertas** [comment]
Filter removed from blog; announcements and quotes now shown only on homepage.

**Comment by sbxchicago** [comment]
Still seeing filter on Blog

**Comment by clararaubertas** [comment]
Should be fixed.
