### ISSUE TITLE
Blog Post: Topics in "More On" header

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#78]
I’d suggest we drop links from “More on Testing, Repro, Doc:” (They appear immediately above as links in metadata and here It creates confusion about whether we link to one location or three)

**Comment by clararaubertas** [comment]
Do you want to keep "More On" header but with the topics not being links, or remove header altogether?

**Comment by sbxchicago** [comment]
What you did is great.
