### ISSUE TITLE
Blog post: Related blog posts

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#79]
- No intro text, no publication date will display in related blog posts. Does Parallactic address or should SBX address in front-end dev?

**Comment by clararaubertas** [comment]
Great, will alter to match wireframes.

**Comment by clararaubertas** [comment]
Altered!

**Comment by sbxchicago** [comment]
I don't see any related blog posts currently. We'll need some to come online to test further.

**Comment by sbxchicago** [comment]
FYI... Blog page is displaying red error page.

**Comment by curfman** [comment]
Added some related blog posts: commit 4a5b6271b8c5d236a2b7381ab494389350f49b38

**Comment by clararaubertas** [comment]
Blog should be functional now, with related blog posts showing where applicable and nothing showing for posts that don't have related posts.
