### ISSUE TITLE
Blog Post: Publication Date

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#80]
I'm not sure if I've been out of the loop or if this is a lingering discrepancy, so I'm addressing both of you:
- The blog post publication date appears to be programmatically generated for page meta data, and included in the body copy. Will this remain if Lois removes from copy? Is there still a use case where Lois would override auto date generation if that date isn’t desirable or is inaccurate?

**Comment by clararaubertas** [comment]
Right now for blog posts, the publication date is taken from the copy (and will change if the copy changes, or disappear if the date disappears from copy). For resources other than blog posts, the publication date is the date of the last commit applied to this file.
Let me know if this is correct, or if you'd like me to change the publish date process for either blog posts or other resources.

**Comment by curfman** [comment]
I agree that current functionality as described above by Clara is what we want:  publication date for blog posts set from copy, and other publication dates set from last commit (generally).  

Question: Do we want to support manual override for publication date to be something other than the last commit (e.g., if last commit is just a minor typo fix, not a content change)?  Likely so.  Would need metadata.

**Comment by bernhold** [comment]
How about two dates: first published and last update?
