### ISSUE TITLE
Forms: Contribute to BSSw & Contact

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#85]
Clara, 

You can refer to the WFs, pgs 28 and 33 for pages with submission forms. Both are the same. How should we proceed with these? Do you take the lead on these?

**Comment by clararaubertas** [comment]
Are the form contents to be sent via email? I can set up forms if so (and text for the pages will be taken from the GitHub content).

**Comment by sbxchicago** [comment]
That's the current plan. Any better idea? Just thinking aloud, but would there a way to feed form content to a Github vehicle? Like an issues list? If no an email would be fine. Probably feedback@bssw.io. I can check with Lois

**Comment by clararaubertas** [comment]
That would be potentially doable but I'm not sure if it would be worthwhile -- let me know what you decide.

**Comment by sbxchicago** [comment]
Are you saying it's time-consuming? Or just an odd request? If time consuming, are we talking more than 2-5 hours ? With that info I can discuss with Lois.

**Comment by clararaubertas** [comment]
Time-consuming -- probably around 5 hours or a little more. Let me know what you think!

**Comment by sbxchicago** [comment]
Hold off  for now.

**Comment by clararaubertas** [comment]
OK -- should we go ahead with setting up the forms as described to email content to feedback@bssw.io ? Let me know, thanks.

**Comment by sbxchicago** [comment]
Yes.

**Comment by clararaubertas** [comment]
Contact form is set up!

**Comment by clararaubertas** [comment]
Waiting on confirmation that forms are good to go!
