### ISSUE TITLE
Events - Expired/None displaying

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#88]
The dates have all expired on the Upcoming events so none are listed. Can you modify dates so that these will display? Any idea why they aren't moving to past events? Should we request to Clara that any expired date moves to Past Events?

**Comment by sbxchicago** [comment]
We could also use a few more events to ensure they are being consistently addressed.

**Comment by curfman** [comment]
Actually 1 event is still upcoming:  https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/Events/Workshop.SE4Science17.md

And I added 1 new upcoming event: https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/Events/Conference.SC17.md

So, we currently have 2 upcoming events and 2 prior events.

**Comment by sbxchicago** [comment]
Hmmm... so they are entered but aren't displaying? I want to double check before alerting Clara.

**Comment by sbxchicago** [comment]
Clara, though there are events in the system it appears listings for Upcoming Events and Past Events are coming up blank
http://bss.parallactic.com/events
http://bss.parallactic.com/events?past=true

**Comment by clararaubertas** [comment]
Just tagging in here to confirm that I'm aware of the bugs with events displaying right now and am working on it.

**Comment by clararaubertas** [comment]
This should be fixed!
