### ISSUE TITLE
Individual Event Page - edits/guidelines

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#89]
- Remove year from event titles unless it is incorrect to do so (the date will appear directly above title) 
- Do you think a deck would ever be applicable? Its in WF, but I want to be sure you will use it.
- No "Overview" title needed
- To match wireframes, add “Event Website” as last link, this will be set off with a button, no URL will display 
- We plan to link to event website a second time below running text. Let SBX know if this is not desirable for some reason. 
- Above any sub-resources listed at bottom of page, a standard label of Highlights should be used.

**Comment by curfman** [comment]
Not sure about the deck question; let's discuss.  Current conference info is cut-and-paste from event websites, which does not generally directly map to short 'deck' text.  But if you recommend this from a design perspective, we can implement this.

Other edits implemented.

Note that the year in some conference names is part of the actual conference name.

**Comment by sbxchicago** [comment]
To be discussed: Decks on individual events
