### ISSUE TITLE
About - Top Deck

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#90]
On About page, the page title and deck should appear in the box, the content that follows appears on white page below

**Comment by clararaubertas** [comment]
Please explain what text exactly is the "deck" on this page. Thanks!

**Comment by sbxchicago** [comment]
The deck is the first paragraph below the page title. Admittedly it needs some trimming.

**Comment by clararaubertas** [comment]
Should be fixed now!
