### ISSUE TITLE
About Page - Content Sections

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#91]
Do you think you can adhere to three sections for this page? They'd be: 
- Site Use Policies
- BSSw Contrbutors
- The BSSw Team

Currently, there is no Site Use Policies header and we will have four large page heads with very little content under each. It's a little awkward. Of course, this approach presumes you agree that Site Use Policies covers both Intended Use of Site and Contributing and Collaborating. LMK if you prefer the current approach.

**Comment by curfman** [comment]
Fixed.  There are separate pages for Policies and Contributors, so assuming we want brief text and a link.  Will get back to you about the Team question.  Thanks.

**Comment by sbxchicago** [comment]
Yes, the brief text and link makes sense. I'm now concerned that Contributors is becoming too much of a blanket term. Case in point is Contributing and Collaborating and Contributors being sequential sections. I think you do mean that the institutions are responsible for getting the site operational and that contributors are contributing to the site. Should we clarify?
