### ISSUE TITLE
Foreign links - homepage and other pages

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#93]
1.
Outdated Get Oriented Links appear in the hero area of the homepage 

The links —  Communities Overview, What Is CSE?, What Is High Performance Computing (HPC)?, Site Overview — should go away.

Lois added new, correct links in the hero area — currently bullets. I'm not sure why but they don't map to the correct pages and the outdated links do. Lois's links are broken actually. For instance: 

Lois's "Site Overview" bullet maps to http://bss.parallactic.com/pages/communities-overview/. A page with this name no longer exists in the repo. It was renamed to CommunitiesOverview.md. I'm guessing you've established a redirect? Although Lois's link is accurate, it creates a routing error. 

If this something that you and Lois discussed and she needs to fix, let me know and you needn't read further. 

2.
The second part of the problem is that I asked for these links to appear on each subpage as subnav. So the incorrect subnav links that appear on the homepage also appear on each page indicated above. So be wary of this as you unravel the "wrong subnav links" problem above. In addition these links appear on the About page. I think this is occurring because About was originally one of these links which might explain why they are appearing. 

3.
The third part of the problem is that these subnav links appear at the bottom of each Get Oriented subpage. They should actually be in the hero box. I think the problem is that the entirety of page content is in the hero box. Just the page title, deck, and subnav should appear in the hero box. 

4. (sorry, yes a number 4!) 
In the WFs we have non-linking "Get Oriented:" text appearing before this subnav. Can you have this appear in each hero that displays this subnavigation and preceding the links?

**Comment by clararaubertas** [comment]
What is a "deck" here?

Lois should remove the links from the page text so that the subnav can be automatically generated.

**Comment by sbxchicago** [comment]
The deck for each of these pages _should be_ the first sentence or two that follow the page title. These are running a little long. Any new paragraph should start page content. Does that help?

I'll ask Lois to remove the links.

Do you have what you need to automatically generate the subnav? Links order is below:
- Site Overview is in first position
- Communities Overview moves to second position
- What Is CSE? becomes Intro to CSE
- What Is High Performance Computing (HPC)? becomes Intro to HPC

**Comment by curfman** [comment]
Clarifying questions for https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/Site/Homepage.md

I removed the bullets for "Site Overview" etc.  Do you also want me to remove the links to these 4 pages?    And then modify the text for the 4 pages so that the first part paragraph of each just 1 or 2 sentences?

Thanks for explaining exactly what is needed.

**Comment by clararaubertas** [comment]
Yes, please remove the links to the pages (we will programmatically add these). 

Can you give an example for one of these pages of what text should be displayed where? Perhaps an updated wireframe page including actual text?

**Comment by sbxchicago** [comment]
I sent you an email with a wireframe on Wednesday.

**Comment by clararaubertas** [comment]
Great, text should now be adjusted.

For the "Get Oriented" subnav -- are you saying the text linking to those pages should be different from the page names?

**Comment by curfman** [comment]
I changed the titles to match the file name:  Intro to CSE, Intro to HPC.

**Comment by clararaubertas** [comment]
OK ! Just to make sure it's clear, there's no need for titles to match filenames, but the titles chosen (i.e. the first heading in each Markdown file) will determine what text is displayed in links.

**Comment by clararaubertas** [comment]
I believe these are now displaying correctly!
