### ISSUE TITLE
Search - search box in top nav

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#95]
We didn't indicate this in WFs but we plan to have any search take place in the nav area near to where the search box is. Click on the search icon and some JS will reveal a search box. 

So the user would never be dropped on the search page the way we are doing with the prototype. 

Can you incorporate the search box functionality into top nav bar?

**Comment by clararaubertas** [comment]
This should be fixed!
