### ISSUE TITLE
Search page - Refine Results

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#96]
Currently the search page displays "Refine Results" dropdown. This would appear on resource listing pages, not search results.

It's possible in a phase 2 that we might consider faceting results between Resources and Prerequisites (WhatIs, HowTo docs). I think that would be the most useful device to sort search results. Let me know if you have other ideas.

**Comment by clararaubertas** [comment]
OK, "Refine Results" moved to "All Resources" page.
