### ISSUE TITLE
Search results - more consistency

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#97]
- In the first 10 results there is repetition between the linked text (first line) and the unlinked text on second line that follows
- last three search results show some odd text/formatting including bullets

**Comment by sbxchicago** [comment]
Search results looking much better now. Two results have carets in front of them and I can't determine why. Is this a sign that something is buggy or something else?
(Searching for Integration Testing)
Two results display this: "> Debugging Testing Continuous integration testing Reproducibility"

**Comment by clararaubertas** [comment]
This should be resolved!
